### ISSUE TITLE
[Bug] 【共享队伍】中选托勒密时无法切换再临阶段

### ISSUE THREAD

**Issue by liuhaotian9420** [chaldea-center/chaldea#115]
### What happened?

从【共享队伍】中选择一个含有托勒密的队伍，队伍内的托勒密会默认为该组队最后的再临阶段
![20240320111427_rec_](https://github.com/chaldea-center/chaldea/assets/57208366/9c851188-b6bb-4563-8152-b1d9d8a7a2c9)
而且在队伍界面重置再临阶段也不能生效
![image](https://github.com/chaldea-center/chaldea/assets/57208366/a407d329-2545-40e9-ace7-661fe36da99f)

### Platform

Windows

### App Version

2.5.7 (968)

### Checklist

- [X] Are you using latest app version? [Release History](https://github.com/chaldea-center/chaldea/releases)

**Comment by SharpnelXu** [comment]
是因为这个队伍上传的时间早于Chaldea支持托勒密的时间，新版本的托勒密队伍没有这个现象
