### ISSUE TITLE
[BUG] Fail to install on Android 12

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#12]
手机平台：Pixel 4a 5G， Android 12，美服playstore。

故障：由于原来是从play上装的Chaldea，所以虽然app提醒可以自己下载新版apk覆盖，也没有照办。
今早看到play上版本有更新，于是更新。
但无法完成更新过程，play提示无法更新，重启手机后问题依旧。
于是卸载Chaldea，从play全新安装，仍然不行（见附图）。
![Screenshot_20211025-103447](https://user-images.githubusercontent.com/12206161/138727198-c9b6caab-0ad3-4025-8fb3-7e44dc8e82c6.jpg)
在github的release页面下载三个版本（x86/armeabi/arm64）安装，全部出现同一个错误“There is a problem parsing the package.”

因此我有点怀疑是不是android 这个版本app本身有什么问题……

**Comment by narumishi** [comment]
1.6.3 released
