### ISSUE TITLE
[Bug] 托勒密 S3 技能开启后被动 5 不生效

### ISSUE THREAD

**Issue by liuhaotian9420** [chaldea-center/chaldea#126]
### What happened?

![20240813102541_rec_](https://github.com/user-attachments/assets/1725c4af-69a2-4b9b-a091-3223ba576cdb)

开启被动 5，且 S3 开启后，冷却依然是 5 且消耗了一次被动5 的效果

### Platform

Windows

### App Version

2.5.12（973）

### Checklist

- [X] Are you using latest app version? [Release History](https://github.com/chaldea-center/chaldea/releases)

**Comment by SharpnelXu** [comment]
Fixed in https://github.com/chaldea-center/chaldea/commit/1436130c2f6f224d9dfa795e69dfebfd6e36a43a
