### ISSUE TITLE
[FEATURE]Support 120Hz ProMotion for iOS 15

### ISSUE THREAD

**Issue by LeoJeson** [chaldea-center/chaldea#14]
开发者大佬好，我的使用平台是iPhone13pro，ios15.1，在软件内部上下滑动时能感受到明显的掉帧现象，感觉有点影响体验，希望大佬条件允许的话能适配一下

**Comment by narumishi** [comment]
- https://github.com/flutter/flutter/issues/90675

我会尝试添加以下到plist中，但似乎添加之后目前仍需要切换开启关闭省电模式来达到120hz，不过我没有120hz设备，无法验证，后续版本可能需要你测试下反馈。
```
    <key>CADisableMinimumFrameDurationOnPhone</key>
    <true/>
```
待官方修复后仍需一定时间才能在beta分支中应用该修复。再加上目前所用的插件在新版本中存在一些bug，暂时固定在flutter2.6 beta版本。

**Comment by narumishi** [comment]
待1.6.4审核通过后可以测试下是否支持ProMotion ~~大概率不行~~

**Comment by LeoJeson** [comment]
> 
我升级后试了一下，确实没开启promotion，反复开关省电模式也无济于事，感觉上下滑动明显掉帧

**Comment by narumishi** [comment]
新增了一些ProMotion相关代码，我稍后上传一个测试版，你到时候在TestFlight里下载，等测试版可下载的时候TestFlight应该会有通知。
https://testflight.apple.com/join/HSyZttrr

**Comment by narumishi** [comment]
想了想用 Xcode 12 好像也编译不出 iOS 15 的特性，升级了 Xcode 13 重新编译了1.6.5+641的版本，已上传至TestFlight

**Comment by LeoJeson** [comment]
> 想了想用 Xcode 12 好像也编译不出 iOS 15 的特性，升级了 Xcode 13 重新编译了1.6.5+641的版本，已上传至TestFlight

试了一下，好像还是没啥效果

**Comment by narumishi** [comment]
那就只能……眨眼补帧了，等待官方支持吧 :confused:

**Comment by ShineYang** [comment]
> 新增了一些ProMotion相关代码，我稍后上传一个测试版，你到时候在TestFlight里下载，等测试版可下载的时候TestFlight应该会有通知。
> 
> https://testflight.apple.com/join/HSyZttrr

下载使用了你 testflight 提供的 app，1.6.5 目前是可以明显感觉到帧率提升的，是在 delegate 强制指定刷新率的吗？

**Comment by LeoJeson** [comment]
> 
 啊？能感受到吗？我的感觉就像是开了全局30Hz一样，全程卡顿

**Comment by LeoJeson** [comment]
> > 新增了一些ProMotion相关代码，我稍后上传一个测试版，你到时候在TestFlight里下载，等测试版可下载的时候TestFlight应该会有通知。
> > https://testflight.apple.com/join/HSyZttrr
> 
> 下载使用了你 testflight 提供的 app，1.6.5 目前是可以明显感觉到帧率提升的，是在 delegate 强制指定刷新率的吗？

啊？能感受到吗？我的感觉就像是开了全局30Hz一样，全程卡顿

**Comment by ShineYang** [comment]
> 
> 
> 
> 
> 
> 
> > > 新增了一些ProMotion相关代码，我稍后上传一个测试版，你到时候在TestFlight里下载，等测试版可下载的时候TestFlight应该会有通知。
> 
> > > https://testflight.apple.com/join/HSyZttrr
> 
> > 
> 
> > 下载使用了你 testflight 提供的 app，1.6.5 目前是可以明显感觉到帧率提升的，是在 delegate 强制指定刷新率的吗？
> 
> 
> 
> 啊？能感受到吗？我的感觉就像是开了全局30Hz一样，全程卡顿

我的设备是 iPhone13 pro max，对比其它 flutter app 是能感觉到帧率高一些的。

**Comment by LeoJeson** [comment]
> > > > 新增了一些ProMotion相关代码，我稍后上传一个测试版，你到时候在TestFlight里下载，等测试版可下载的时候TestFlight应该会有通知。
> > 
> > 
> > > > https://testflight.apple.com/join/HSyZttrr
> > 
> > 
> > > 
> > 
> > 
> > > 下载使用了你 testflight 提供的 app，1.6.5 目前是可以明显感觉到帧率提升的，是在 delegate 强制指定刷新率的吗？
> > 
> > 
> > 啊？能感受到吗？我的感觉就像是开了全局30Hz一样，全程卡顿
> 
> 我的设备是 iPhone13 pro max，对比其它 flutter app 是能感觉到帧率高一些的。

我是13p，绝了

**Comment by narumishi** [comment]
@ShineYang 用了上述issue里的方法，delegate里设置了帧率范围和prefer值。不过也有说不一定保证生效的 ~_~ 
不确定的是是否始终维持120帧，不然比较耗电。

@LeoJeson 但是30Hz是不是夸张了点？之后我添加个帧率显示直观点

**Comment by LeoJeson** [comment]
> @ShineYang 用了上述issue里的方法，delegate里设置了帧率范围和prefer值。不过也有说不一定保证生效的 ~_~ 不确定的是是否始终维持120帧，不然比较耗电。
> 
> @LeoJeson 但是30Hz是不是夸张了点？之后我添加个帧率显示直观点

我也说不清，主观感觉像是30，有啥能直观显示当前帧率的方法吗

**Comment by narumishi** [comment]
@LeoJeson iOS自身有没有不清楚，我稍后在app里加一个显示功能，不过等苹果审核大概又得等好久。。。

**Comment by narumishi** [comment]
@ShineYang @LeoJeson 
1.6.5. build 642已可下载, 显示帧率功能开启方式：**关于Chaldea-长按logo-返回设置页 底部即可出现相关选项**
~~有些debug功能只能在debug模式下运行~~

几点说明：
1. 当页面无组件需要刷新时，默认锁10帧
2. 60帧应该没问题……我的古董6s都有最高60帧
3. 测试能否达到120Hz附近，若能，是否始终维持在120Hz(而非动态适配)

**Comment by LeoJeson** [comment]
> @ShineYang @LeoJeson 1.6.5. build 642已可下载, 显示帧率功能开启方式：**关于Chaldea-长按logo-返回设置页 底部即可出现相关选项** ~有些debug功能只能在debug模式下运行~
> 
> 几点说明：
> 
> 1. 帧率取得过去30帧的平均值
> 2. 当页面无组件需要刷新时，默认锁10帧
> 3. 60帧应该没问题……我的古董6s都有最高60帧
> 4. 测试能否达到120Hz附近，若能，是否始终维持在120Hz(而非动态适配)

我这里还是build641，我再等等吧

**Comment by narumishi** [comment]
昨天有史以来第一次秒审核，~~然后发现居然还要手动通知测试者才算正式测试~~ 现在可以了应该

**Comment by LeoJeson** [comment]
> 昨天有史以来第一次秒审核，~然后发现居然还要手动通知测试者才算正式测试~ 现在可以了应该

woc，成功了！本来我点进去上下滑动，都是60，整体在10～60浮动，最高60；我寻思录屏吧，点完录屏之后就解锁120了全程丝滑，滑动时帧数不低于125。然后我寻思开关省电模式，发现有9成概率能解锁120。但是也发现，当我把app切换到后台，过一会再切回来的时候，又变成强制锁60了，最高不超过65，需要再切换省电模式。
ps，我用手快速滑动屏幕并将手指从屏幕上移开，画面继续滑动的过程中为全程稳定120，应该非动态适应（我觉得非常好）。
总之就是非常nb

**Comment by narumishi** [comment]
先凑合着用吧，剩下的我也只能等flutter啥时候正式支持了
列表不滚动的时候是否依旧为120hz？

**Comment by LeoJeson** [comment]
> 先凑合着用吧，剩下的我也只能等flutter啥时候正式支持了
> 列表不滚动的时候是否依旧为120hz？

会逐渐稳定到10

**Comment by narumishi** [comment]
不需要刷新的时候能降低帧率是最好的了，否则比较耗电
~~可惜我还未曾体验过120帧的流畅顺滑~~

**Comment by ShineYang** [comment]
> 先凑合着用吧，剩下的我也只能等flutter啥时候正式支持了
> 
> 列表不滚动的时候是否依旧为120hz？

刚测试了下，不滑动稳定10，滑动最高120，请问是如何实现的动态调整？

**Comment by narumishi** [comment]
> > 先凑合着用吧，剩下的我也只能等flutter啥时候正式支持了
> > 列表不滚动的时候是否依旧为120hz？
> 
> 刚测试了下，不滑动稳定10，滑动最高120，请问是如何实现的动态调整？

我也没干什么，flutter自己适配的。。。
1. 在`info.plist`中加入`CADisableMinimumFrameDurationOnPhone`
https://github.com/chaldea-center/chaldea/commit/6205567e3736c531b5016dafc449bef82bebeaac
2. 然后再delegate中指定帧率范围
https://github.com/chaldea-center/chaldea/commit/d31735ba043c799a1afd2ef93bd1283f65c98445

**Comment by ShineYang** [comment]
Thx，我尝试一下> > > 先凑合着用吧，剩下的我也只能等flutter啥时候正式支持了
> 
> > > 列表不滚动的时候是否依旧为120hz？
> 
> > 
> 
> > 刚测试了下，不滑动稳定10，滑动最高120，请问是如何实现的动态调整？
> 
> 
> 
> 我也没干什么，flutter自己适配的。。。
> 
> 1. 在`info.plist`中加入`CADisableMinimumFrameDurationOnPhone`
> 
> https://github.com/chaldea-center/chaldea/commit/6205567e3736c531b5016dafc449bef82bebeaac
> 
> 2. 然后再delegate中指定帧率范围
> 
> https://github.com/chaldea-center/chaldea/commit/d31735ba043c799a1afd2ef93bd1283f65c98445
> 
>

**Comment by narumishi** [comment]
突然发现几年前的iPad Pro10.5(iOS14.6)就已经有ProMotion了…… 上述指定帧率代码在iOS14中应该没有被执行就已经可以支持120hz，为什么iPhone上的就不行。。。

**Comment by ShineYang** [comment]
> 突然发现几年前的iPad Pro10.5(iOS14.6)就已经有ProMotion了…… 上述指定帧率代码在iOS14中应该没有被执行就已经可以支持120hz，为什么iPhone上的就不行。。。

iOS15.2更新后，帧率设置貌似失效了

**Comment by narumishi** [comment]
@ShineYang 把iPad试了下升级15.2，还是有120帧的 ==、

**Comment by ShineYang** [comment]
> @ShineYang 把iPad试了下升级15.2，还是有120帧的 ==、

目前应该是 flutter 单纯的不支持 iPhone 的promotion

**Comment by narumishi** [comment]
TestFlight 1.8.1+810 应该已经支持120Hz了。
