### ISSUE TITLE
Can you add a search bar in the master missions tab?

### ISSUE THREAD

**Issue by duradara** [chaldea-center/chaldea#15]
Basically the title. A search bar will make using this much better.

And also maybe can you put the traits in alphabetical order?

Sorry if my english is bad

**Comment by narumishi** [comment]
I will consider to add mission target search. It may take some time to be done due to no time recently.

As for traits sorting,  the filter of servant list? If so, it could be supported later.

**Comment by duradara** [comment]
Thx
