### ISSUE TITLE
[BUG] `windowsInfo() has not been implemented` caused by device_info_plus plugin

### ISSUE THREAD

**Issue by duradara** [chaldea-center/chaldea#16]
**Describe the bug**
Just installed the lastres version and this happend, I also tried manualy downloading the update from githud and it also happens

**Screenshots**
![Capture](https://user-images.githubusercontent.com/50158352/143724027-58c33799-173c-43cf-9ac3-46b658535b48.PNG)

**Desktop (please complete the following information):**
 - OS:Windows 7

**Comment by narumishi** [comment]
Sorry, I have checked on all other platforms, but only windows is forgot

**Comment by narumishi** [comment]
So strange, it is a plugin issue. But cannot figure out the reason. 🙁

**Comment by narumishi** [comment]
- https://github.com/fluttercommunity/plus_plugins/issues/600

**Comment by narumishi** [comment]
I have temporally disable the bug, please download from gitee and have a test:
 https://gitee.com/chaldea-center/chaldea/releases/v1.6.4+640

If it works, I will upload it to github release.

Finally, keep the issue open until the plugin fixed the bug.

**Comment by duradara** [comment]
Just download it and it seems to e working fine.

**Comment by narumishi** [comment]
I will track the issue in another place, close it.
