### ISSUE TITLE
[BUG] Null check operator used on a null value

### ISSUE THREAD

**Issue by a08381** [chaldea-center/chaldea#17]
**Describe the bug**
通过Charles导入https抓包出错

**To Reproduce**
1. 使用Charles抓包
2. 将包保存到手机上
3. 通过Chaldea导入

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2505002/145250006-f2369508-15d8-495e-8b47-ea2ab30bd078.png)

**Smartphone (please complete the following information):**
 - Device: iPhoneSE
 - OS: iOS 15.3
 - App Version 1.6.4(640)

**Additional context**

附上我抓包获得的数据，[这个是以前抓的能正常导入的](https://pan.shadniw.ml/0:/ssl/ssl.txt)，[这个是刚抓的有问题的](https://pan.shadniw.ml/0:/ssl/sslss.txt)

**Comment by a08381** [comment]
干，为啥突然又可以正常导入了

**Comment by narumishi** [comment]
既然偶尔出现这个问题，肯定是哪里有潜在的bug，国服和日服的数据格式是有差别的，我觉得还是有必要检查一下。
能否再贴个日志，或者在应用反馈中点下反馈。

**Comment by a08381** [comment]
> 既然偶尔出现这个问题，肯定是哪里有潜在的bug，国服和日服的数据格式是有差别的，我觉得还是有必要检查一下。
> 
> 能否再贴个日志，或者在应用反馈中点下反馈。

iOS中的日志应该去哪里找？

**Comment by narumishi** [comment]
原因应该是你在进入导入https页面后，后台于00时32分更新了数据版本1206->1209，其中于1207更新了国服翻译`虹の糸玉: 彩虹线团->虹之线球`，导致该素材没有找到。如果重进该页面应该就解决了问题。
