### ISSUE TITLE
[FEATURE] Can you support the Korean server?

### ISSUE THREAD

**Issue by Munung** [chaldea-center/chaldea#18]
I'm sorry I don't have language skills

do you have any plans to support the Korean server?
Koreans are using this app really well but it's not translated, so they are having a hard time.

**Comment by narumishi** [comment]
In next major version, I will refactor project to support more languages(including KR). But I know nothing about Korean, so I need someone to help me with the translation.
- #19

**Comment by Munung** [comment]
> In next major version, I will refactor project to support more languages(including KR). But I know nothing about Korean, so I need someone to help me with the translation.
> - #19 


Which one should I translate?
Is this right?
https://github.com/chaldea-center/chaldea/tree/master/lib/l10n

**Comment by narumishi** [comment]
yes, I will generate a arb file for Korean later - `intl_ko.arb`
You can translate from English or Chinese to Korean, you should limit the length of translated words, a similar character count with Chinese version is desired.

Also there are more translations in codes. It will be discussed later.

Have you already join the discord server?

**Comment by Munung** [comment]
I just joined the discord server

**Comment by narumishi** [comment]
Please see the discussion in translation channel
