### ISSUE TITLE
[FEATURE]关于从者强化本以及强化素材显示的建议

### ISSUE THREAD

**Issue by LeoJeson** [chaldea-center/chaldea#2]
大佬好！新人master，请多指教[doge]！最近一直在用您的app，平台为iPhone 11 pro，ios15b4，1.5.1版本，截至2021.8.6为最新版本。有一些小建议不知大佬能否考虑一下？
![IMG_0215](https://user-images.githubusercontent.com/62548782/128444957-aef37886-3c40-42b4-919b-6e88755aba9e.PNG)
ru
如图，在微信上的素材规划小程序实现了在强化本下，给出了具体的活动名，不知道大佬是否方便实现此类效果；

又如，在阿尔托莉雅（caster）下，从者技能显示如下：
![IMG_0216](https://user-images.githubusercontent.com/62548782/128445309-6fa19495-35ea-48d0-bfbf-75f09cc32eeb.PNG)
个人感觉容易让人误会，以为是有强化本

最后，在强化技能的时候，貌似只能看单个技能所需素材，而不能自动看到全部的所需素材。打个比方，如果把技能从9.9.9升级到10.10.10，貌似不能直接看到3个传承结晶+60M的qp，而是要自己计算单个技能所需素材，手动叠加，感觉有一些麻烦（也可能是我还没找到

最后，感谢大佬开发的程序，祝大佬呼符出货，迦里人丁兴旺！我先star为敬。

**Comment by narumishi** [comment]
抱歉刚看到……万万没想到真的会有人开issue😂
1. 把技能本图标换成文字标签一直想换了，自从日服越来越多花里胡哨的东西之后。但按照material design 切换按钮太占地方一直没想好怎么布局弄好看点……
2. 开放时间等资料其实一开始就从mc wiki上录入了，理由同上，一直纠结布局没弄……
3. 可以考虑下添加个按钮查看当前从者的所有消耗，现在只有在实施强化前有个预览，问题不大
4. 欢迎分享 ^_<

**Comment by narumishi** [comment]
close issue since already implemented
