### ISSUE TITLE
[BUG]在素材规划中出现的全0条目

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#21]
见画线处，如果全都是0，为什么需要规划完成这个副本……

**Screenshots**
见附件
![Screenshot 2021-12-12 153718](https://user-images.githubusercontent.com/12206161/145730651-11162ef2-56aa-4f7b-9ae8-e32ee7689b4b.png)

 - OS: Windows 10
 - App Version 1.6.4 640

**Comment by narumishi** [comment]
因为非整数线性规划的结果往往都是小数，比如打2次海德公园可能原先是打1.8次，此处使用向上取整。
其次掉落也是，2次海德公园掉落期望是0.5书页左右，显示掉落期望的时候就向下取整成0了。

**Comment by narumishi** [comment]
当<1时，就显示小数
fixed 7c56e03da27c500a10012a8b02d5b833cc073def
![image](https://user-images.githubusercontent.com/56487872/145798691-8714c223-8174-4365-9c34-b8eff6a0416f.png)

**Comment by dajusha** [comment]
> 当<1时，就显示小数 fixed [7c56e03](https://github.com/chaldea-center/chaldea/commit/7c56e03da27c500a10012a8b02d5b833cc073def) ![image](https://user-images.githubusercontent.com/56487872/145798691-8714c223-8174-4365-9c34-b8eff6a0416f.png)

感谢修改
