### ISSUE TITLE
[BUG] import error

### ISSUE THREAD

**Issue by SekiBetu** [chaldea-center/chaldea#23]
**Describe the bug**
import error

**To Reproduce**
1. Go to import page
2. Click on import userdata.json/*.json

**Expected behavior**
sucessfully imported

**Screenshots**
![image](https://user-images.githubusercontent.com/38283893/146091430-cb43131e-322d-40f4-8163-ad999bd48984.png)

**Smartphone (please complete the following information):**
 - Device: Redmi K30 Pro Zoom
 - OS: MIUI12.5(Android 11)
 - App Version: v1.6.4+640

**Comment by narumishi** [comment]
7f07fa312a6fd71f94a36a7a07f88b85a8a303c8
fixed but havent released

**Comment by narumishi** [comment]
temp solution, directly replace `data_folder/user/userdata.json` or restore through server backup
