### ISSUE TITLE
[FEATURE] 规划功能的改进

### ISSUE THREAD

**Issue by SekiBetu** [chaldea-center/chaldea#24]
**Is your feature request related to a problem? Please describe.**
现在的数据导入后，默认会把所有的喜爱标记的从者都加进规划里

**Describe the solution you'd like**
规划功能应该分离，喜爱应该是当做拥有从者的功能而不是规划功能，与那个微信小程序素材规划一样，单独筛选和导入喜爱的从者进行规划
![Screenshot_2021-12-16-06-46-49-294_com tencent mm](https://user-images.githubusercontent.com/38283893/146281065-08aeaebf-1c43-4f0a-8483-067049b18654.jpg)

**Comment by SekiBetu** [comment]
看懂了，这是逆向思维，刚才没弄懂，那没事了，就是感觉怪怪的，表一直不变，变得是规划

**Comment by SekiBetu** [comment]
能不能实现默认隐藏没有规划的从者

**Comment by SekiBetu** [comment]
在规划里，筛选里面条件设为规划未满的时候，会筛选出当前规划以外的角色

**Comment by narumishi** [comment]
目前确实是拥有即等于加入规划，当然状态共享，各规划仅目标值不同。~~已经全图鉴了所以才开不开fav筛选都一样吗~~
此设计最初来源于①我要全部999 ②偷懒。不过favorite一开始是支持不同规划各自设置。后来因为某种原因~~忘了~~设成共享当前状态了。相当于只要添加个owned属性，如果要改应该不太复杂。


> 在规划里，筛选里面条件设为规划未满的时候，会筛选出当前规划以外的从者

规划未满包括了灵基/主动/附加/灵衣/圣杯等任何一项未达到目标值，再次确认下你**筛选出规划外的从者**或者举例贴图看下？

**Comment by narumishi** [comment]
目前确实是拥有即等于加入规划，当然状态共享，各规划仅目标值不同。~~已经全图鉴了所以才开不开fav筛选都一样吗~~
此设计最初来源于①我要全部999 ②偷懒。不过favorite一开始是支持不同规划各自设置。后来因为某种原因~~忘了~~设成共享当前状态了。相当于只要添加个owned属性，如果要改应该不太复杂。


> 在规划里，筛选里面条件设为规划未满的时候，会筛选出当前规划以外的从者

规划未满包括了灵基/主动/附加/灵衣/圣杯等任何一项未达到目标值，再次确认下你**筛选出规划外的从者**或者举例贴图看下？

**Comment by SekiBetu** [comment]
> 目前确实是拥有即等于加入规划，当然状态共享，各规划仅目标值不同。~已经全图鉴了所以才开不开fav筛选都一样吗~ 此设计最初来源于①我要全部999 ②偷懒。不过favorite一开始是支持不同规划各自设置。后来因为某种原因~忘了~设成共享当前状态了。相当于只要添加个owned属性，如果要改应该不太复杂。
> 
> > 在规划里，筛选里面条件设为规划未满的时候，会筛选出当前规划以外的从者
> 
> 规划未满包括了灵基/主动/附加/灵衣/圣杯等任何一项未达到目标值，再次确认下你**筛选出规划外的从者**或者举例贴图看下？

![Screenshot_2021-12-16-06-27-08-045_cc narumi chaldea](https://user-images.githubusercontent.com/38283893/146274723-dd90e18b-df4b-41a0-b647-7d586b198c04.jpg)
![Screenshot_2021-12-16-06-27-17-723_cc narumi chaldea](https://user-images.githubusercontent.com/38283893/146274730-8bd3b78b-3b9c-4d1b-a6c1-986ad2885690.jpg)
![Screenshot_2021-12-16-06-27-29-640_cc narumi chaldea](https://user-images.githubusercontent.com/38283893/146274733-d7c07ae2-6b4b-4b0f-a610-5019b2da37ee.jpg)
![Screenshot_2021-12-16-06-27-37-395_cc narumi chaldea](https://user-images.githubusercontent.com/38283893/146274735-9350a947-acbf-44c6-9f50-021ecd5f61bf.jpg)
![Screenshot_2021-12-16-06-27-44-645_cc narumi chaldea](https://user-images.githubusercontent.com/38283893/146274737-846e2918-30e4-4fd5-a51d-f5bec533dae5.jpg)
![Screenshot_2021-12-16-06-27-49-846_cc narumi chaldea](https://user-images.githubusercontent.com/38283893/146274739-341ca9ba-907f-4099-88fb-2bc19b97ccab.jpg)
![Screenshot_2021-12-16-06-28-03-171_cc narumi chaldea](https://user-images.githubusercontent.com/38283893/146274740-5d074aa2-5dbd-4ee8-9425-860c3620c15e.jpg)
规划1234我是按全部，五星，四星，三二一星这样规划的，然后筛选选未满，在规划二三四里面出现了没有规划的从者

**Comment by SekiBetu** [comment]
那些没有红色标注的就是当前规划里没有规划过的从者，仍然出现在了当前规划里 且规律随机，没看懂

**Comment by SekiBetu** [comment]
还有就是貌似不能重置规划，重置规划的功能会把本来的数据也清空而不是重置规划

**Comment by SekiBetu** [comment]
![Screenshot_2021-12-16-06-39-32-280_cc narumi chaldea](https://user-images.githubusercontent.com/38283893/146275924-da4451f3-1c49-402a-aace-fc1700dc565b.jpg)
下面那排按钮太靠右了，我的手机上显示不完整，截图上完整，实际手机圆角把最后升10的按钮切掉了一半

**Comment by SekiBetu** [comment]
现在这种糅合状态不是太舒服，还是学微信小程序，规划和数据分开吧，太乱了

**Comment by SekiBetu** [comment]
找到问题了，是芙芙在导入数据的时候自动默认规划1000
现在有这么个思路：重置规划的功能希望应用在所有可能性的那些规划功能上，然后加入一个筛选后的界面上从者的一键重置规划功能 可以方便很多

**Comment by SekiBetu** [comment]
![Screenshot_2021-12-16-07-16-37-268_cc narumi chaldea](https://user-images.githubusercontent.com/38283893/146279702-65514f92-7087-43ea-872b-6ef022267a03.jpg)
我话有点多，这个强化功能是啥意思，属于是单个从者的所需素材计算嘛

**Comment by narumishi** [comment]
鼓掌鼓掌:clap: 从发现问题到找到问题到解决问题一条龙服务是多么难得！
- [ ] `拥有`和`规划`分开可以采纳，但兼容性考虑在下个大版本实现
- [ ] 芙芙羁绊不加入`规划未满`判断。芙芙最初其实只有金芙芙规划，所以默认值是1000的满银芙芙。之后有人要求加入银芙芙后就没变更。同样类似的是羁绊。这两者还是不参与`规划未满`的筛选比较合适，本身不多用且若加入列表显示会更臃肿。
- [ ] 后续希望加入自选规划项，比如我可以屏蔽圣杯芙芙羁绊纹章等花里胡哨的东西，既不显示也不参与规划。~~不过不是近期~~
- [ ] 重置规划：目前只有单个从者重置规划，重置规划是已经包含了芙芙等在内的，只是如前述默认值不合适。在`规划`页加入`清空当前规划`和类似统一设定的`重置已显示从者的规划`可以很方便的添加。
- [ ] 此外，例如提到的不小心规划错误的情况，如果有撤销功能就比较好，但采用的json/类直接存取数据，比较无脑可以多平台，但实现不了撤销恢复功能。如果有什么好的经验方法，欢迎赐教。

怎么说呢，这东西差不多成型能用的时候我已经接近全迦999用不到了，分享出来后也没多少人反馈，一直处于得过且过的状态:joy:

**Comment by highway007** [comment]
希望规划可以重命名，或者添加备注。时间一长就忘记规划的是什么了

**Comment by narumishi** [comment]
@highway007 已添加
513c837ecc2584161bed6079ea74b43206f3a7ef

**Comment by narumishi** [comment]
@SekiBetu 思来想去，如果把规划分离，按照小程序的办法，每次我添加新从者都得在从者和规划里设置一边，感觉比较麻烦。而且规划依赖手动添加，无法保证同步（很容易修改后忘记同步增删操作）。
优先级1~5的设置是否能满足你的需求？由于默认优先级1，你可以针对不同从者设置不同优先级，计算规划时可以筛选优先级。

**Comment by SekiBetu** [comment]
> @SekiBetu 思来想去，如果把规划分离，按照小程序的办法，每次我添加新从者都得在从者和规划里设置一边，感觉比较麻烦。而且规划依赖手动添加，无法保证同步（很容易修改后忘记同步增删操作）。 优先级1~5的设置是否能满足你的需求？由于默认优先级1，你可以针对不同从者设置不同优先级，计算规划时可以筛选优先级。

规划一打开，全是无关从者，很影响观看，自始至终就这么一个问题而已，如果只显示进行过规划的从者就好了

**Comment by narumishi** [comment]
暂时在设置里加了一项，规划页默认选中规划未满的从者。
虽然和你的意图亿些些差别。

**Comment by narumishi** [comment]
我觉得已经弃疗了这部分，不动了
