### ISSUE TITLE
[Minor Bug/Error] Hunting Quests Part IX (9) displaying as IV (4)

### ISSUE THREAD

**Issue by IvoryLifthrasir** [chaldea-center/chaldea#27]
**Describe the bug**
Well not a bug per se, just a minor error - wrong numeration of HQs. Should be labeled as IX instead of IV

**To Reproduce**
1. Go to 'Event'
2. Click on 'Limited Event' tab
3. Scroll down to 'Dance Torunament...' - the HQ is right below it

**Expected behavior**

**Screenshots**
[Screenshot here](https://i.imgur.com/zULAMIs.png)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - App Version 1.6.6 + 660

**Comment by narumishi** [comment]
Thanks, a typo in parser. The dataset will be fixed in the next update.
