### ISSUE TITLE
[FEATURE] In the statistics page can you add a filter to show only materials needed for ascensions or skill upgrades?

### ISSUE THREAD

**Issue by duradara** [chaldea-center/chaldea#28]
Here is a shitty edit I made about what I am taling about: 
![Capture](https://user-images.githubusercontent.com/50158352/147884726-4fd4a909-e837-4814-8701-62fd15c92968.PNG)

**Comment by narumishi** [comment]
I will consider it after v2 migration, but not now

**Comment by narumishi** [comment]
This is what it will look like, but sure only in V2.
![image](https://user-images.githubusercontent.com/56487872/160723210-d46f03aa-7ba4-49d8-8dc9-8d1d5475baf3.png)

**Comment by duradara** [comment]
> This is what it will look like, but sure only in V2. ![image](https://user-images.githubusercontent.com/56487872/160723210-d46f03aa-7ba4-49d8-8dc9-8d1d5475baf3.png)

Nice

**Comment by narumishi** [comment]
close since already added in V2.
