### ISSUE TITLE
[BUG]日服 极级修炼场已经不是20AP了……

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#29]
对规划影响挺重要的。

Windows 10
 - App Version 1.6.6 660
![2022-01-10_12-57-23](https://user-images.githubusercontent.com/12206161/148823312-7823c256-ecff-41e1-96a0-1e5bd31ee529.png)

**Comment by narumishi** [comment]
啊这，，，效率剧场居然AP算的是新年减半值，有亿丝丝费解，下午更新一下

**Comment by narumishi** [comment]
已更新
https://github.com/chaldea-center/chaldea-dataset/releases/tag/20220111-1.6.0
