### ISSUE TITLE
An appreciation

### ISSUE THREAD

**Issue by LucasRaimund** [chaldea-center/chaldea#3]
Guys i just want to thank you deeply from my heart for your application i truly truly truly  love your amazing work ❤️❤️❤️
Thank you so very much , I'll share your application with many people interested in Fate
Arigato gozaimasu ❤️

**Comment by narumishi** [comment]
Wow, Thank you so much for your affirmation. I'm so pleased that the app is helpful for you all. Please keep the passion on Chaldea and Fate.٩(๑>◡<๑)۶
「Chaldea」をご利用いただき、誠にありがとうございます。
