### ISSUE TITLE
[FEATURE] Remember more page settings

### ISSUE THREAD

**Issue by BlaztOne** [chaldea-center/chaldea#31]
**Is your feature request related to a problem? Please describe.**
I'm annoyed whenever I have to change "AP rate" to "Drop rate", this is dumb + time-consuming.
(This setting is in "Material X"-> "Free Quest" )
**Describe the solution you'd like**
Just make it automatically remember to set it like the last time it did 
Ex: I set my option to Drop rate, so in the next time, when I go to the "Free Quest" tab, it'll automatically set it to Drop rate. But if I switched it into AP rate, in the next time , it'd automatically set it to AP rate.
**Describe alternatives you've considered**

**Additional context**

**Comment by narumishi** [comment]
Got it. I will improve it in the future.

**Comment by narumishi** [comment]
added in 1.6.8
