### ISSUE TITLE
[BUG] Font render issue and disable permission_hanlder on windows  

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#38]
**To Reproduce**
设置如图1，结果如图2

**Screenshots**

 - Device: Pixel 4a 5g
 - OS: Android 12
![Screenshot_20220314-203959](https://user-images.githubusercontent.com/12206161/158289222-9e528f4f-6d18-4c04-840c-d3efeb12bc27.jpg)
![Screenshot_20220314-203950](https://user-images.githubusercontent.com/12206161/158289227-3eab0f8b-43ad-4f0e-a494-d816de0c8a16.jpg)

 - App Version 1.6.8 2681 arm64-v8a

**Comment by narumishi** [comment]
V2前的最后一个版本❌
V2前的最后亿个版本✓

因为改变了小数的默认显示方式，其他地方可能还有类似的显示问题，集齐七个bug召唤新版

**Comment by dajusha** [comment]
> V2前的最后一个版本❌ V2前的最后亿个版本✓
> 
> 因为改变了小数的默认显示方式，其他地方可能还有类似的显示问题，集齐七个bug召唤新版

好的，另外关于win版本：
更新后汉字显示变奇怪了，似乎是字体的原因？
![2022-03-14_20-55-51](https://user-images.githubusercontent.com/12206161/158290742-e1c50f74-1413-451e-9723-b277ebb3a21a.jpg)

这个版本加上了地理位置需求是为了什么……
![2022-03-14_20-56-51](https://user-images.githubusercontent.com/12206161/158290818-94b949f8-0eb0-4871-a543-0ce62681941f.jpg)

**Comment by narumishi** [comment]
字体额我也没改过，可能是升级了框架版本的问题，看着像在使用日文字体。随缘看看解决方案。
地理位置的话，应该是插件的问题，permission_handler用于处理在Android和iOS上的储存照片等权限，最近插件更新了下新增了windows版，可能默认使用所有能用的api，需要手动禁用

**Comment by narumishi** [comment]
另外已知bug：导入抓包错误
加油再找几个bug

**Comment by narumishi** [comment]
```c
#include <winrt/Windows.Devices.Geolocation.h>
#include <winrt/Windows.Devices.Bluetooth.h>
#include <winrt/Windows.Devices.Radios.h>
```
目前permission_handler调用了以上三个接口，暂未找到禁用方法~~除了回滚~~。windows部分也是这个月刚添加的，给他点时间完善吧==、

字体的原因大概找到了，现在locale顺序是【jp, chs, cht, en, ko】，应该是先从日文字符集里找那个字，找到就用日文字体渲染。突然想起来以前有人说日文的字体怪，就应该是以前是按照中文->日文的顺序查找。。。。

**Comment by dajusha** [comment]
> ```c
> #include <winrt/Windows.Devices.Geolocation.h>
> #include <winrt/Windows.Devices.Bluetooth.h>
> #include <winrt/Windows.Devices.Radios.h>
> ```
> 
> 目前permission_handler调用了以上三个接口，暂未找到禁用方法~除了回滚~。windows部分也是这个月刚添加的，给他点时间完善吧==、
> 
> ~字体的原因大概找到了，现在locale顺序是【jp, chs, cht, en, ko】，应该是先从日文字符集里找那个字，找到就用日文字体渲染。突然想起来以前有人说日文的字体怪，就应该是以前是按照中文->日文的顺序查找。。。。~ 猜错了 原因未知
> 
> 该部分数字显示bug已修复

试用 1.6.9 690 版：
苹果数字显示正常了
字体还那样怪怪的

另：win版的前两个版本中，点击检查更新之后跳出有可更新的对话框，如果点击右下最右边按钮来更新的话，会有错误提示一堆文字跳出来，忘了截图，我就点去下载页来下压缩包自己解压。现在1.6.9没有可更新了不能再现，只好在这里说明一下。

**Comment by narumishi** [comment]
@dajusha 如果你没有卸载过的话，在app反馈里填写并发送一下 我看下日志里有没有相关信息

**Comment by dajusha** [comment]
> @dajusha 如果你没有卸载过的话，在app反馈里填写并发送一下 我看下日志里有没有相关信息

已发

**Comment by dajusha** [comment]
> ```
> ├ #0   DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:628)
> │ #1   _rootRunBinary (dart:async/zone.dart:1450)
> │ #2   _CustomZone.runBinary (dart:async/zone.dart:1342)
> │ #3   _FutureListener.handleError (dart:async/future_impl.dart:174)
> │ #4   Future._propagateToListeners.handleError (dart:async/future_impl.dart:778)
> │ #5   Future._propagateToListeners (dart:async/future_impl.dart:799)
> │ #6   Future._completeError (dart:async/future_impl.dart:609)
> │ #7   _SyncCompleter._completeError (dart:async/future_impl.dart:60)
> ├ DioError [DioErrorType.other]: SocketException: Failed host lookup: 'github.com.cnpmjs.org' (OS Error: 不知道这样的主机。
> , errno = 11001)
> Source stack:
> #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473)
> #1      DioMixin.request (package:dio/src/dio_mixin.dart:468)
> #2      DioForNative.download (package:dio/src/entry/dio_for_native.dart:84)
> #3      AutoUpdateUtil.startDownload (package:chaldea/modules/extras/updates.dart:376)
> #4      AutoUpdateUtil.checkAppUpdate (package:chaldea/modules/extras/updates.dart:326)
> <asynchronous suspension>
> 
> ├ [2022-03-14 17:29:04.382][ERROR] error check app update
> ```
> 
> 对于国内用户，之前走的cnpmjs的github代理，看了下目前应该这个代理挂了导致下载github release失败

这个国内用户是怎么判断的……是因为使用简中界面么？
因为我现在地理和游戏服务器都不涉及国内。

**Comment by narumishi** [comment]
在设置-游戏数据里有一项下载源，server或GitHub。

**Comment by dajusha** [comment]
> 在设置-游戏数据里有一项下载源，server或GitHub。

谢谢，改了

**Comment by narumi147** [comment]
- https://github.com/flutter/flutter/issues/103811
