### ISSUE TITLE
[FEATURE] some feature requests

### ISSUE THREAD

**Issue by narumi147** [chaldea-center/chaldea#39]
Here I will post some new feature requests from users' feedback. 
But I have to work on more basic function migration first. So not sure when will be implemented.

If you(have github account) have new feature request, please file a new issue.

- [x] Da Vinci workshop (Mana Prism & Rare Prism), by SORA@discord
- [x] exclude items in shop to bypass item statistics

**Comment by duradara** [comment]
This thing #28

**Comment by BlaztOne** [comment]
Make Plans more viable. Switching to a new plan still shows the servants from the old plan (big visual issue, annoying as hell) ; Not to mention that even when I remove the servants manually, it also remove the corresponding servants from the old plan

**Comment by narumishi** [comment]
@BlaztOne You may have some misunderstanding on **Plan**, it is used for the same servant collection but different plan targets. These plans should belong to the same account. So the owned servants are the same.

If you want to do absolutely different plan for different account. You can goto "Settings-Game Account" then create a new one.

**Comment by BlaztOne** [comment]
It would be nice if you added the damage calculation feature ( I don't mind approximate results )

**Comment by SekiBetu** [comment]
Would it be difficult to synchronize backups using github repositories？

**Comment by narumishi** [comment]
> Would it be difficult to synchronize backups using github repositories？
> 
> just like IntelliJ IDEA and vscode's settings

https://docs.github.com/en/rest/repos/contents#create-or-update-file-contents
using Github API?

**Comment by narumishi** [comment]
But how to ensure synchronization is a more annoying stuff, like dealing with remote and local conflicts. That's why I didn't add "sync" into current app, just manual upload and download.

**Comment by SekiBetu** [comment]
> But how to ensure synchronization is a more annoying stuff, like dealing with remote and local conflicts. That's why I didn't add "sync" into current app, just manual upload and download.

no need to auto-sync, just provide a way to upload and download to a github repositories, I don't trust the sustainability of current cloud backups, github repositories are a good solution

**Comment by narumishi** [comment]
> > But how to ensure synchronization is a more annoying stuff, like dealing with remote and local conflicts. That's why I didn't add "sync" into current app, just manual upload and download.
> 
> no need to auto-sync, just provide a way to upload and download to a github repositories, I don't trust the sustainability of current cloud backups site, github repository is a better solution

Added, have a try

**Comment by SekiBetu** [comment]
> > > But how to ensure synchronization is a more annoying stuff, like dealing with remote and local conflicts. That's why I didn't add "sync" into current app, just manual upload and download.
> > 
> > 
> > no need to auto-sync, just provide a way to upload and download to a github repositories, I don't trust the sustainability of current cloud backups site, github repository is a better solution
> 
> Added, have a try

![image](https://user-images.githubusercontent.com/38283893/172585780-eb5816f0-6026-4fab-8d24-b65df7b1fb55.png)

![image](https://user-images.githubusercontent.com/38283893/172585757-088a9feb-8b21-4739-96e9-10bca43e1224.png)

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/172586536-c3a0542a-3529-444f-8f5b-a90952d2f42e.png)
![image](https://user-images.githubusercontent.com/38283893/172586566-4ab58c2f-698e-4999-aec7-ec03864da6dd.png)
it's not saveing correctly

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/172586987-92ac69ce-166a-479a-a75a-471dd8c1b0b5.png)
![image](https://user-images.githubusercontent.com/38283893/172587026-85f00eb1-a01b-47d0-af70-79ff3f9fa25f.png)
the branch name is taking place the repo name

**Comment by SekiBetu** [comment]
and what does the path means? do i need to create a dir on the repo?

**Comment by narumishi** [comment]
@SekiBetu the editable page is correct, the other one is display issue. And you have to add **path** which is the filepath in your repo. Talk in discord pls.

**Comment by SekiBetu** [comment]
> @SekiBetu the editable page is correct, the other one is display issue. And you have to add **path** which is the filepath in your repo. Talk in discord pls.

![image](https://user-images.githubusercontent.com/38283893/172587669-d5fa62d8-2ec9-4205-a719-bef48e4fb78f.png)
thanks, it's working.

**Comment by narumi147** [comment]
Closing since Da Vinci shop is implemented.
