### ISSUE TITLE
Web App: "invalid argument" error when attempting to update database

### ISSUE THREAD

**Issue by BarbacoaBurrito** [chaldea-center/chaldea#40]
Web app is not usable due to database update error. Stops at 99% at throws up the following error. Tried on both Firefox and Chrome.
![Capture](https://user-images.githubusercontent.com/97126132/159967476-64e9b558-b76f-44c5-b6b4-24a452d915d5.PNG)

**Comment by narumishi** [comment]
sorry, I forgot to publish updates to production. 
The github action is down for now, the build will be available once github team solve it.
https://www.githubstatus.com/

**Comment by narumishi** [comment]
It's up, please refresh it again.

**Comment by narumishi** [comment]
:thinking: detailed description?

**Comment by BarbacoaBurrito** [comment]
I can click on prev and it will take me to the previous screen, I can swipe back to the previous screen, but I can't click on done or swipe forward. The mouse doesn't turn into the hand w/ index finger when I hover over Done either.

**Comment by narumishi** [comment]
Can you attach the screenshot too?

**Comment by BarbacoaBurrito** [comment]
My cursor isn't include in the screenshot but you can see at the bottom that "PREV" is selected when I hover over it, so there's something for me to click on. "DONE" doesn't exhibit the same behavior.
![image](https://user-images.githubusercontent.com/97126132/159977191-db38b837-0119-4ca2-9d3e-dfd2e50ecbc2.png)

**Comment by narumishi** [comment]
This is desktop browser? press F12 or right click "Inspect" to open dev tool, goto console tab. Can you copy all printed messages?

![image](https://user-images.githubusercontent.com/56487872/159980856-60048cec-3368-4268-b979-f104c353c3fd.png)

**Comment by narumishi** [comment]
And another strange thing, why the page(icon/tiles/update now btn) and button bar(PREV/pagination/DONE) don't layout the same center? If possible, capture the full screenshot.

**Comment by narumishi** [comment]
If no more information provided, I will close it in 3 days.
