### ISSUE TITLE
Update URL of FGO Sim

### ISSUE THREAD

**Issue by TohnoCoding** [chaldea-center/chaldea#41]
FGO Sim URL has been updated to https://fgosim.github.io/Material/ -- I believe it should be updated as well in the next release of Chaldea app to avoid confusion, since the Webcrow link will stop working in the near future.

**Comment by narumishi** [comment]
Thanks, url updated. 
![image](https://user-images.githubusercontent.com/56487872/160722599-2842cb22-15b2-40fc-851e-e27f11644101.png)
