### ISSUE TITLE
[Bug]:  cn.chaldea.center 似乎无法账户同步

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#42]
### What happened?

我从v1导出数据json文件，使用A机器的浏览器在 https://cn.chaldea.center 注册用户，使用设置里的从v1数据导入，使用相对正常（从者和材料读取到了）。但是使用B机器的浏览器登录在A注册的用户，并无任何信息，和新帐户一样。

### Platform

- [X] web
- [ ] ios
- [ ] android
- [ ] windows
- [ ] linux
- [ ] macOS

### Device Info

Win10

### Which game server is related to this issue?

JP, NA

### App Version

v2 web

**Comment by narumishi** [comment]
数据不会自动同步，依旧是存在本地的，仍旧需要在用户数据里进行 上传 和 下载
如果自动同步，没法控制好同步频率或时机，且cf有每日请求数限制，还是选择了手动同步

**Comment by dajusha** [comment]
> 数据不会自动同步，依旧是存在本地的，仍旧需要在用户数据里进行 上传 和 下载 如果自动同步，没法控制好同步频率或时机，且cf有每日请求数限制，还是选择了手动同步

懂了，那就当这个不存在就是了……

**Comment by narumishi** [comment]
手动同步功能和以前客户端一样，不怎么便利，没有改进也没有退化，大概。
