### ISSUE TITLE
Effect Descriptor and DataVals display

### ISSUE THREAD

**Issue by narumi147** [chaldea-center/chaldea#43]
The skill/NP effects are parsed from raw data. So there may be mistakes or confusing description.
Please leave comments here with screenshot to show the mistakes.

**Comment by narumishi** [comment]
## Rate/UseRate - add `Chance` to avoid confusing
![image](https://user-images.githubusercontent.com/56487872/162610578-eefba610-fcea-4fad-95d5-5426a5efe3cb.png)
![image](https://user-images.githubusercontent.com/56487872/162610583-d2a75f19-f78a-48db-bc5c-bf7a7cded116.png)
