### ISSUE TITLE
[Bug]: Material Calculation Issue on V2

### ISSUE THREAD

**Issue by BlaztOne** [chaldea-center/chaldea#46]
### What happened?

- Basically, this is the first time I've downloaded V2. The new features are nice, new effects and better GUI. However, after 2 minutes of using, I recognized that the material calculation is incorrect. My Kojirou and oberon is already 10/10/10 but the required materials for active skills is still calculated.
- I even turned on " Subtract Owned " option, and the problem was still there.
- Another thing to add, many of my servants get ignored( Like Chiron in the picture below ). As you can see, Chiron doesn't get added into the "Active Skill" section despite him having his face on my plan
Hope you fix this.
[
![image](https://user-images.githubusercontent.com/69741876/163672021-8aad3bde-e23e-4d39-8bdc-0504fa364ce3.png)
](url)
[
![image](https://user-images.githubusercontent.com/69741876/163672036-999e0f45-dbef-4952-9d0f-2455bed4d747.png)
](url)
[
![image](https://user-images.githubusercontent.com/69741876/163672100-27046961-2244-403e-b7de-7fa6043a5e63.png)
](url)
[
![image](https://user-images.githubusercontent.com/69741876/163672116-be3ec09c-60f5-45b8-9b14-b4f559fe34a8.png)
](url)
[
![image](https://user-images.githubusercontent.com/69741876/163672168-46aa6fa8-a24a-485f-a0ba-ea03123ca0f9.png)
](url)
[
![image](https://user-images.githubusercontent.com/69741876/163672180-aff360ee-e836-4b3a-ba61-a9366a3138fa.png)
](url)

### Platform

- [ ] web
- [ ] ios
- [ ] android
- [X] windows
- [ ] linux
- [ ] macOS

### Device Info

Windows 8.1

### Which game server is related to this issue?

JP

### App Version

V2 1.8.0(800)

**Comment by narumishi** [comment]
How terrible, can you send a feedback in app? let me check the logs and data.

**Comment by narumishi** [comment]
Fixed, that's a display bug, the calculation is correct. You can download new version from https://github.com/chaldea-center/chaldea/releases/tag/canary
