### ISSUE TITLE
[Bug]: Database update doesn't work

### ISSUE THREAD

**Issue by BlaztOne** [chaldea-center/chaldea#47]
### What happened?

Spammed on the "update now" button, nothing happened except the fact that the app ate more RAM
Reopened the launcher, still didn't work
Ah, I couldn't close the app normally without task manager (I used to be able to)
[
![image](https://user-images.githubusercontent.com/69741876/163718463-b056121c-1a78-4065-bf5f-f3219df9d51a.png)
](url)

### Platform

- [ ] web
- [ ] ios
- [ ] android
- [X] windows
- [ ] linux
- [ ] macOS

### Device Info

Windows 8.1

### Which game server is related to this issue?

JP

### App Version

V2

### Relevant log output

```shell
type '_GrowableList<dynamic>' is not a subtype of type 'List<int>'
```

**Comment by narumishi** [comment]
fixed

**Comment by BlaztOne** [comment]
Opening this again.
A new Database bug
[
![image](https://user-images.githubusercontent.com/69741876/164955151-2e1953e1-dfae-4ffa-a15d-addd94f1a77f.png)
](url)

**Comment by narumishi** [comment]
Just wait, I am updating new schema now.

**Comment by narumishi** [comment]
Published, wait about 15min for new build.
