### ISSUE TITLE
[Bug]: Material Displaying Problem; Real Calculation Problem?

### ISSUE THREAD

**Issue by BlaztOne** [chaldea-center/chaldea#48]
### What happened?

- Remember my "Material Calculation Problem" ?
- That thing is still here, newest update by the way.
[
![image](https://user-images.githubusercontent.com/69741876/163800357-8a876109-709a-4880-950e-60037ce20c82.png)
](url)
[
![image](https://user-images.githubusercontent.com/69741876/163800385-9da18d39-7062-467e-b257-f81d981f7ecf.png)
](url)
- And now it's even worse, the fruit of longevity had DISAPPEARED (the material that got displayed wrongly) after I returned to the main statistic page (As I checked the statistics page, each materials one by one again, it appears to be fine now)
![image](https://user-images.githubusercontent.com/69741876/163800592-a15546a4-b64f-40f8-a19d-a9d4019b0b99.png)
- And I'm wondering if this is actually a calculation bug or not (Arash third skill costs 1.6M not 1M) 
[
![image](https://user-images.githubusercontent.com/69741876/163800792-e75b8c79-98f5-4216-940a-5728c0884f04.png)
](url)
[
![image](https://user-images.githubusercontent.com/69741876/163800827-f6110c08-db84-4f2a-a43c-228d67414411.png)
](url)
- Cu Proto Active Skills cost only 7M, the calculation is not ok at all
[
![image](https://user-images.githubusercontent.com/69741876/163801213-5f118d1b-8aa3-4b36-871c-60d6da92b865.png)
](url)
- His second skill alone costs more than 8M!
[
![image](https://user-images.githubusercontent.com/69741876/163801269-5b1cad6e-7451-41b1-9a25-42a386eec221.png)
](url)
- Hope you fix those bugs and add auto-update, since it doesn't work in V2.

 

### Platform

- [ ] web
- [ ] ios
- [ ] android
- [X] windows
- [ ] linux
- [ ] macOS

### Device Info

Windows 8.1

### Which game server is related to this issue?

JP

### App Version

V2 1.8.0(800) 0cc875

**Comment by narumishi** [comment]
let me have a check.

-----
You can reply in the previous issue, I will reopen it. no need to open two issues with the same problem.

As for auto-update, it's *preview* now, the new canary version will be build once I changed the codes.  the version number(1.8.0+800) may be the same. So even I added auto-update, you cannot detect new version.

**Comment by narumishi** [comment]
The qp calc is wrong, it is overridden not added, so for each part(active/append/ascension) it only shows the qp cost of last level.

as for fruit item: in image 1, you are in ***Consumed*** tab. and in image 3, you are in ***Demand*** tab.

**Comment by narumishi** [comment]
Download the new version, it should be fixed.

**Comment by BlaztOne** [comment]
Alright, delete this thread
