### ISSUE TITLE
[Bug]: Incorrect number of coins in the overview table

### ISSUE THREAD

**Issue by NoAvalon** [chaldea-center/chaldea#49]
### What happened?

There's a problem with the number of coins being displayed in the servant coins table.

![image](https://user-images.githubusercontent.com/50183903/164299029-a29e6078-acff-4ec1-ae44-29af29b7d107.png)

It shows that for a 30 coins servant (permanent SR or limited R servant) at NP1 and bond 1 I'd receive **65** coins.
This however is incorrect as it'd be 30 coins from NP1 + 5 coins from bond 1 resulting in **35** coins total.

This isn't an issue only with the 30 coins servants. This issue is present throughout the entire table. For every combination the sum is always adding one more NP level on top and therefore needs to be lowered. I hope that can be fixed.

There's one more thing I was wondering about. When I looked at higher NP levels I noticed that there are numbers in italic. They seem to start around the 470-480 mark and continue afterwards.

![image](https://user-images.githubusercontent.com/50183903/164300009-5599284a-212b-4cf8-87e9-ba639ffbb2f5.png)

I'm not sure if that should indicate something or if that's just a display error. I'd appreciate if you could clarify what that means.

### Platform

- [ ] web
- [ ] ios
- [X] android
- [X] windows
- [ ] linux
- [ ] macOS

### Which game server is related to this issue?

JP, NA

### App Version

v1.7.0+700

**Comment by narumishi** [comment]
ah yeah, the value for NP1 here is actually for NP2. Will be fixed in V2.

**Comment by narumishi** [comment]
It has been fixed in V2. Download from canary release please.
