### ISSUE TITLE
[Bug]: 三小时前的win版本自动更新把我的数据干没了……

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#51]
### What happened?

打开chaldea发现没有从者设置了，去设置一看当前帐号是Gudako，就知道坏了。查了下log，仅有的变化就是canary自动升级了。

### Platform

Windows

### App Version

Chaldea Preview

### Relevant log output

```shell
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:188)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:197)
├ [2022-04-24 18:16:35.395][INFO] Unique ID: 45D6AA3B-04C8-5AF6-B663-E98B087C1576
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:79)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:199)
├ [2022-04-24 18:16:35.409][INFO] Resolved app version: cc.narumi.chaldea 1.7.0+700
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 18:16:35.874][DEBUG] fetch gamedata version: DataVersion(2022-04-22T14:04:18, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 18:16:59.453][DEBUG] fetch gamedata version: DataVersion(2022-04-24T13:47:19, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:188)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:197)
├ [2022-04-24 19:04:24.439][INFO] Unique ID: 45D6AA3B-04C8-5AF6-B663-E98B087C1576
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:79)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:199)
├ [2022-04-24 19:04:24.441][INFO] Resolved app version: cc.narumi.chaldea 1.7.0+700
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 19:04:24.681][DEBUG] fetch gamedata version: DataVersion(2022-04-24T13:47:19, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 19:04:36.172][DEBUG] fetch gamedata version: DataVersion(2022-04-24T13:47:19, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:107)
│ #1   <asynchronous suspension>
├ 已经是最新版本
├ [2022-04-24 19:04:36.196][ERROR] load gamedata(false)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   _BootstrapPageState.onDataReady.<anonymous closure> (package:chaldea/app/modules/home/bootstrap.dart:347)
│ #1   _BootstrapPageState.onDataReady.<anonymous closure> (package:chaldea/app/modules/home/bootstrap.dart:346)
├ [2022-04-24 19:04:36.196][DEBUG] silent background update error
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:188)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:197)
├ [2022-04-24 21:50:29.226][INFO] Unique ID: 45D6AA3B-04C8-5AF6-B663-E98B087C1576
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:79)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:199)
├ [2022-04-24 21:50:29.230][INFO] Resolved app version: cc.narumi.chaldea 1.7.0+700
└-----------------------------------------------------------------------------------------------------------------------
├ #0   _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
│ #1   _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
│ #2   _parseJson (dart:convert-patch/convert_patch.dart:36)
│ #3   JsonDecoder.convert (dart:convert/json.dart:612)
│ #4   JsonCodec.decode (dart:convert/json.dart:216)
│ #5   jsonDecode (dart:convert/json.dart:155)
│ #6   JsonHelper.loadModel (package:chaldea/utils/json_helper.dart:30)
│ #7   <asynchronous suspension>
├ FormatException: Unexpected end of input (at character 1)

^

├ [2022-04-24 21:50:29.276][ERROR] failed to load UserData? json model
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 21:50:29.305][DEBUG] fetch gamedata version: DataVersion(2022-04-24T13:47:19, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 21:50:44.945][DEBUG] fetch gamedata version: DataVersion(2022-04-24T13:47:19, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:107)
│ #1   <asynchronous suspension>
├ 已经是最新版本
├ [2022-04-24 21:50:44.946][ERROR] load gamedata(false)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   _BootstrapPageState.onDataReady.<anonymous closure> (package:chaldea/app/modules/home/bootstrap.dart:347)
│ #1   _BootstrapPageState.onDataReady.<anonymous closure> (package:chaldea/app/modules/home/bootstrap.dart:346)
├ [2022-04-24 21:50:44.946][DEBUG] silent background update error
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:188)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:197)
├ [2022-04-24 21:51:35.643][INFO] Unique ID: 45D6AA3B-04C8-5AF6-B663-E98B087C1576
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:79)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:199)
├ [2022-04-24 21:51:35.646][INFO] Resolved app version: cc.narumi.chaldea 1.7.0+700
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 21:51:35.803][DEBUG] fetch gamedata version: DataVersion(2022-04-24T13:47:19, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 21:51:47.733][DEBUG] fetch gamedata version: DataVersion(2022-04-24T13:47:19, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:107)
│ #1   <asynchronous suspension>
├ 已经是最新版本
├ [2022-04-24 21:51:47.733][ERROR] load gamedata(false)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   _BootstrapPageState.onDataReady.<anonymous closure> (package:chaldea/app/modules/home/bootstrap.dart:347)
│ #1   _BootstrapPageState.onDataReady.<anonymous closure> (package:chaldea/app/modules/home/bootstrap.dart:346)
├ [2022-04-24 21:51:47.733][DEBUG] silent background update error
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:188)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:197)
├ [2022-04-24 22:05:52.380][INFO] Unique ID: 45D6AA3B-04C8-5AF6-B663-E98B087C1576
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:79)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:199)
├ [2022-04-24 22:05:52.382][INFO] Resolved app version: cc.narumi.chaldea 1.7.0+700
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 22:05:52.540][DEBUG] fetch gamedata version: DataVersion(2022-04-24T13:47:19, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:101)
├ [2022-04-24 22:06:04.597][DEBUG] fetch gamedata version: DataVersion(2022-04-24T13:47:19, 43 files)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:107)
│ #1   <asynchronous suspension>
├ 已经是最新版本
├ [2022-04-24 22:06:04.597][ERROR] load gamedata(false)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   _BootstrapPageState.onDataReady.<anonymous closure> (package:chaldea/app/modules/home/bootstrap.dart:347)
│ #1   _BootstrapPageState.onDataReady.<anonymous closure> (package:chaldea/app/modules/home/bootstrap.dart:346)
├ [2022-04-24 22:06:04.597][DEBUG] silent background update error
└-----------------------------------------------------------------------------------------------------------------------
```

**Comment by dajusha** [comment]
去dropbox把历史版本恢复了，真的吓人

**Comment by dajusha** [comment]
恢复之后又有新问题，从者的升级计划还在，但是不反应到素材缺乏量，也就是每个素材的需求都是0.
尝试随便找一个从者把技能1计划加一级，回去看素材体现出来了这个小改动，但是已有的计划：升等级0-4，技能000到101010，全都不体现在素材需求上

**Comment by dajusha** [comment]
> 恢复之后又有新问题，从者的升级计划还在，但是不反应到素材缺乏量，也就是每个素材的需求都是0. 尝试随便找一个从者把技能1计划加一级，回去看素材体现出来了这个小改动，但是已有的计划：升等级0-4，技能000到101010，全都不体现在素材需求上

啊这个bug重启app后正常了

**Comment by dajusha** [comment]
去看了下版本记录的时间戳，是19：04发生的：
![FireShot Capture 153 - 版本历史记录_ - https___www dropbox com_history_-t](https://user-images.githubusercontent.com/12206161/165017461-6253047b-56b5-493b-923c-772f00156d61.png)

**Comment by narumishi** [comment]
1 和canary更新无关，应该是在保存数据时发生了错误，导致之后读取的数据也是错误的，比如保存中意外关闭程序，虽然我已经设置了关闭前先写入数据+200ms延时。难道是别的原因……

2 是从哪里导入的数据？导入-v2 或其他地方，我可能漏了统计表更新

**Comment by narumishi** [comment]
诶不对，你这是还是旧版1.7.0，我刚说的关闭前保存是在1.8.0+版本里，1.8是2.0的预览版。
canary是预览版不提供自动更新。

**Comment by dajusha** [comment]
> 诶不对，你这是还是旧版1.7.0，我刚说的关闭前保存是在1.8.0+版本里，1.8是2.0的预览版。 canary是预览版不提供自动更新。

感觉不对，因为看旧版的log没啥问题，出事的那个时间我没有用旧版。

├ #0   AutoUpdateUtil.patchGameData._reportResult (package:chaldea/modules/extras/updates.dart:96)
│ #1   AutoUpdateUtil.patchGameData (package:chaldea/modules/extras/updates.dart:129)
├ [2022-04-11 14:20:58.748][ERROR] fail to patch: 已经是最新版本
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AutoUpdateUtil.checkAppUpdate (package:chaldea/modules/extras/updates.dart:295)
│ #1   _GalleryPageState.initState.<anonymous closure> (package:chaldea/modules/home/gallery_page.dart:32)
├ [2022-04-11 14:21:01.839][INFO] No update: fetched=null, cur=1.7.0 (700)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AutoUpdateUtil.patchGameData._reportResult (package:chaldea/modules/extras/updates.dart:96)
│ #1   AutoUpdateUtil.patchGameData (package:chaldea/modules/extras/updates.dart:129)
├ [2022-04-11 17:27:43.014][ERROR] fail to patch: 已经是最新版本
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AutoUpdateUtil.checkAppUpdate (package:chaldea/modules/extras/updates.dart:295)
├ [2022-04-11 17:27:56.613][INFO] No update: fetched=null, cur=1.7.0 (700)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:188)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:197)
├ [2022-04-24 22:04:43.734][INFO] Unique ID: 45D6AA3B-04C8-5AF6-B663-E98B087C1576
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:79)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:199)
├ [2022-04-24 22:04:43.737][INFO] Resolved app version: cc.narumi.chaldea 1.7.0+700
└-----------------------------------------------------------------------------------------------------------------------
├ #0   Database.loadUserData (package:chaldea/components/config.dart:140)
│ #1   _ChaldeaState.initState (package:chaldea/modules/chaldea.dart:70)
├ [2022-04-24 22:04:43.973][DEBUG] userdata loaded.
└-----------------------------------------------------------------------------------------------------------------------
├ #0   Database.loadGameData (package:chaldea/components/config.dart:166)
│ #1   _ChaldeaHomeState.afterFirstLayout (package:chaldea/modules/chaldea.dart:253)
├ [2022-04-24 22:04:49.609][DEBUG] game data loaded, version 20220325.
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AutoUpdateUtil.patchGameData._reportResult (package:chaldea/modules/extras/updates.dart:96)
│ #1   AutoUpdateUtil.patchGameData (package:chaldea/modules/extras/updates.dart:129)
├ [2022-04-24 22:04:53.181][ERROR] fail to patch: 已经是最新版本
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AutoUpdateUtil.checkAppUpdate (package:chaldea/modules/extras/updates.dart:295)
│ #1   _GalleryPageState.initState.<anonymous closure> (package:chaldea/modules/home/gallery_page.dart:32)
├ [2022-04-24 22:04:56.062][INFO] No update: fetched=null, cur=1.7.0 (700)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AutoUpdateUtil.patchGameData._reportResult (package:chaldea/modules/extras/updates.dart:96)
│ #1   AutoUpdateUtil.patchGameData (package:chaldea/modules/extras/updates.dart:129)
├ [2022-04-24 22:05:05.018][ERROR] fail to patch: 已经是最新版本
└-----------------------------------------------------------------------------------------------------------------------



可以看出旧版最后启动是4月11日，出了毛病之后我在4.24晚十点又打开看看。
而数据被毁是4.24的晚七点，这个时间只能够在上边楼贴的preview版生成的log里找到操作。

**Comment by narumishi** [comment]
确实是新版的1.7.0，当时preview没有更新版本号。

最近的一个错误是21:50当地时间，如果19:04上传到云盘，那错误肯定还早，不知道你的云盘同步间隔多久。或者你把完整的log文件附上来。

```
├ [2022-04-24 21:50:29.230][INFO] Resolved app version: cc.narumi.chaldea 1.7.0+700
└-----------------------------------------------------------------------------------------------------------------------
├ FormatException: Unexpected end of input (at character 1)

^

├ [2022-04-24 21:50:29.276][ERROR] failed to load UserData? json model
```

**Comment by dajusha** [comment]
> 确实是新版的1.7.0，当时preview没有更新版本号。
> 
> 最近的一个错误是21:50当地时间，如果19:04上传到云盘，那错误肯定还早，不知道你的云盘同步间隔多久。或者你把完整的log文件附上来。
> 
> ```
> ├ [2022-04-24 21:50:29.230][INFO] Resolved app version: cc.narumi.chaldea 1.7.0+700
> └-----------------------------------------------------------------------------------------------------------------------
> ├ FormatException: Unexpected end of input (at character 1)
> 
> ^
> 
> ├ [2022-04-24 21:50:29.276][ERROR] failed to load UserData? json model
> ```

dropbox没有同步间隔，有修改就是即时的，所以在dropbox的文件版本记录里19：04被破坏的json文件也就应该只能是19：04的app操作导致，我想。
[log.log](https://github.com/chaldea-center/chaldea/files/8556574/log.log)
上边这个是preview的log
下边这个是旧版的log
[log.log](https://github.com/chaldea-center/chaldea/files/8556579/log.log)

**Comment by narumishi** [comment]
19.04这次大概用了多久关闭的应用？19:04:24.439启动，1min内就关闭了？

**Comment by dajusha** [comment]
> 19.04这次大概用了多久关闭的应用？19:04:24.439启动，1min内就关闭了？

这个说实在不记得具体时长了，只能知道这次启动没有进行主动数据修改，就是想看一下御主任务解法，结果打开看到过了晚七点但是app内没有更新美服任务，就关了，所以也就一两分钟。
10点多想要改个什么才又打开，发现了问题。

**Comment by dajusha** [comment]
> 1.8.x增加了 "关闭前先保存+200ms延时" 现在又增加了备份，也就是原先的userdata.json一个文件，现在是userdata.json和userdata.json.bak文件，读取时如果第一个失败则读第二个。 这样应该或许可能可以把意外错误降低几个数量级了吧 🤣

好哦……
这次我这边出现的问题是写入失败造成的么？即使我没有修改数据？

**Comment by narumishi** [comment]
我是这么猜的，因为10点钟读取的时候是一个空文件，应该是写入时出错，因为正常写入时文件内容会被“清空”然后再写入保存。
至于没有修改，一般不会触发保存，有部分页面是特定操作触发，其余是每个10秒检测若有变化则保存

**Comment by dajusha** [comment]
谢谢解答
那么，
1. 本次写入出错的原因是否能够找到？
2. “增加了备份，也就是原先的userdata.json一个文件，现在是userdata.json和userdata.json.bak文件” 事实上是写入两个不同的文件。假设特定条件导致写入json文件出错，那么写入bak是不是也会出错（

**Comment by narumishi** [comment]
1. 不知道，前面说了猜测是关闭应用的时候正在写入，导致意外中止
2. 如果json写入失败，就不会进行bak的写入，相当于被打断了。此时json可能是本次损坏的，bak是上一次的。

如果文件实际上写入失败/错误但是在应用中并没有报错，也就是程序认为是写成功了，这种情况应该很稀有吧……

**Comment by dajusha** [comment]
也行吧，至少按照新功能来说，出了同样问题的话，bak是上回修改的，不会完全损失数据，空了的json会被app跳过直接读bak。

那么没有能够进一步解决的问题了，请关闭issue

**Comment by dajusha** [comment]
> 我也想知道完美方案==、

因为写入能出错误，那么进一步增加多个自动备份文件循环覆盖的话……又增加了写入量又增加了关闭时的延迟操作时长，出问题的几率反而增加了。

不如让大家都把整个app文件夹放到dropbox或者onedrive里省事，有啥损失直接恢复json（

**Comment by narumishi** [comment]
在backup文件夹里，每天(>24h)会自动备份一份。出错可以从这里找回。

**Comment by dajusha** [comment]
> 在backup文件夹里，每天(>24h)会自动备份一份。出错可以从这里找回。
![Screenshot 2022-04-25 141214](https://user-images.githubusercontent.com/12206161/165157892-f854f902-0a04-441b-b80e-80bdb4c72bc1.png)


新版这边没有哦……事故之前的居然一个都没有。

去旧版看了眼确实有一些。

**Comment by narumishi** [comment]
因为事故前你用的1.7.0每日备份应该处于禁用状态==、
从旧版往新版迁移的时候，很多功能因为两边不兼容或重构未完成等原因禁用了，~~等想起来了~~逐步启用。。。
