### ISSUE TITLE
[Bug]: 剧情限制四星从者的卡池问题

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#52]
### What happened?

打开app，从者中选择加藤段藏，点选卡池页面，可发现几乎列出了所有可能存在的卡池，而非UP其的卡池。
回到从者列表，使用筛选“剧情限定”，尝试查看其它剧情限定从者，32号术元帅也有同样bug。
打开win版app，确认同样有此bug。

### Platform

Android

### Which game server is related to this issue?

NA

### App Version

preview（22.4.24更新那个）

**Comment by narumishi** [comment]
是把礼装当从者了233

**Comment by dajusha** [comment]
所以这数据库是手工一个个标记的么……

**Comment by narumishi** [comment]
MC扒的，只是判断是否有up出了点问题

**Comment by narumishi** [comment]
fixed
