### ISSUE TITLE
[Bug]: Fail to download data

### ISSUE THREAD

**Issue by Smilucifer** [chaldea-center/chaldea#57]
### What happened?

Describe the details and upload screenshots if necessary

### Platform

iOS

### Device Info

ios 15.5

### Which game server is related to this issue?

CN

### App Version

2.0.0

### Relevant log output

```shell
Return "Invalid argument(s): 'appendSkill' is not one of the supportedvalues"
```

**Comment by narumishi** [comment]
New data deployed.
