### ISSUE TITLE
[Bug]: 计算素材的free本进度选项中251和252文字是一样的。

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#58]
### What happened?

此处下拉选项中两个2.5没有文字区别，看了下android也一样，虽然不影响使用……

![Screenshot 2022-05-28 160704](https://user-images.githubusercontent.com/12206161/170842956-5f54032f-86a3-4f38-b5f1-5c6f88927a8c.png)

### Platform

Android, Windows

### App Version

2.0.1.902

**Comment by narumishi** [comment]
加了个后缀（仅限此页）
<img width="432" alt="image" src="https://user-images.githubusercontent.com/56487872/170885482-e0de24c3-30d5-477d-8ff3-f659f69d106d.png">

**Comment by dajusha** [comment]
> 加了个后缀（仅限此页） <img alt="image" width="432" src="https://user-images.githubusercontent.com/56487872/170885482-e0de24c3-30d5-477d-8ff3-f659f69d106d.png">

好～

**Comment by narumishi** [comment]
~~顺便发现了一处没有翻译的~~
