### ISSUE TITLE
[FEATURE] Can you add a way to switch accounts to the top of the main screen?

### ISSUE THREAD

**Issue by duradara** [chaldea-center/chaldea#6]
So we dont have to go to go to the options just to xhange our accounts

![Capture](https://user-images.githubusercontent.com/50158352/132105383-b9637d3b-c4f0-4f40-9a06-45329765e3cc.PNG)

**Comment by narumishi** [comment]
Although I think it's not so suitable to place it here. Anyway, I have added, but you need to switch it on inside display settings. 
Next version 1.5.6 will be released recent.
![image](https://user-images.githubusercontent.com/56487872/132135352-5896ec14-bcaf-4be5-825d-a45c0085e0cd.png)
------
![image](https://user-images.githubusercontent.com/56487872/132135359-b9819f0e-ad23-4fb3-96e5-ffc3bdc9e8ae.png)

**Comment by narumishi** [comment]
close since 1.5.6 published
