### ISSUE TITLE
[FEATURE SUGGESTION] Statistics page: Display demand targets below material demands

### ISSUE THREAD

**Issue by TohnoCoding** [chaldea-center/chaldea#60]
Similar to what the old FGO Material Simulator used to do, I believe it'd be useful to display a sort of general overview of the desired targets in terms of materials and QP.

**Suggested feature:**
Under the list of materials in the Demands tab of the Statistics page, a general overview of the selected character targets should be displayed in order to have better at-a-glance knowledge of the current status of the account in terms of achieved and in-progress targets.

**Suggested alternative:**
A detailed breakdown of *all* involved units in a second page instead of a breakdown per material.

**Example results:**
Something similar to this: https://imgur.com/a/66dZbpC

**Comment by narumishi** [comment]
Since there are too many plan targets, for normal item: active/append/ascension/costume, it may still take one row per servant. otherwise, each servant's width is different(e.g. some has costume and some not).
So I'm afraid the layout maybe similar with "Plan" list page, sure less info here.

Or if you already has detailed design in your mind, you can show me a simple draft/sketch about your suggested layout?

**Comment by narumishi** [comment]
The webcrow one is `<svtI><skill1><skill2><skill3>`
and your mentioned one is `<svt><item list>`? Maybe I misunderstood >_<.

> scroll left/right if the amount of materials for a single Servant is too large (which theoretically SHOULDN'T HAPPEN, but better be safe than sorry).

**Comment by TohnoCoding** [comment]
True, MatSim does it `<Servant><skill1><skill2><skill3>`.
Chaldea could do it `<Servant><QP><item1 amount="##"><item2 amount="##">...<itemX amount="##">`, and have each Servant or each entire row be clickable to expand their details (X stuff for Active Skills, Y stuff for Append Skills, Z stuff for Costume unlock, etc.) as a way to break down the material amount values at the top. That way I think could even make redundant the individual pages when clicking on a single material.

Something like this: https://imgur.com/a/GYCTp1X
Each row or Servant could be clickable for a specific breakdown of what they need.

**Comment by TohnoCoding** [comment]
Decided to post a new comment and delete the old once since I don't know if Github notifies for edits, so Narumi gets to see the image I updated. Entirety of previous comment below:

True, MatSim does it `<Servant><skill1><skill2><skill3>`.
Chaldea could do it `<Servant><QP><item1 amount="##"><item2 amount="##">...<itemX amount="##">`, and have each Servant or each entire row be clickable to expand their details (X stuff for Active Skills, Y stuff for Append Skills, Z stuff for Costume unlock, etc.) as a way to break down the material amount values at the top. That way I think could even make redundant the individual pages when clicking on a single material.

EDIT: Had some extra time to flesh out the idea a bit more. Image is still crappy but I think it conveys better what I'm trying to say.

Something like this: https://i.imgur.com/z1hVQvj.png _(updated image)_
Each row or Servant could be clickable for a specific breakdown of what they need.

**Comment by narumishi** [comment]
Great, that would be more clear 👍🏻 I will try to add it in recent.

~~and no notification for edit.~~

**Comment by narumishi** [comment]
Any idea?

<img width="375" alt="image" src="https://user-images.githubusercontent.com/56487872/173197332-643e058b-35bb-44a5-878e-8409c39c446a.png">

**Comment by TohnoCoding** [comment]
Looking amazing!

**Comment by narumishi** [comment]
You can have a try at preview version, and any feedback is better

**Comment by TohnoCoding** [comment]
Holy crap, it _**LITERALLY**_ doesn't get any better than this! Amazing work!

![image](https://user-images.githubusercontent.com/98242280/173570739-97beda59-130c-4b43-8c8a-f86ab7177ac2.png)

**Comment by TohnoCoding** [comment]
When can we expect a stable release? Because this is literally more than perfect in every way to get a proper overview/bird's eye of mat requirements. I'm loving it!

![image](https://user-images.githubusercontent.com/98242280/173709643-010348c7-f40d-4316-99d6-2df409765d57.png)

**Comment by narumishi** [comment]
JP has some new stuff in today's update. I will release it after implemented the new things.

If you are using windows, you can just use preview build now, only android preview uses the different apk package name.

**Comment by narumishi** [comment]
2.0.5 released.
