### ISSUE TITLE
[Bug]: 在android上用7小时前的2.0.5 906安装包apk覆盖15号下载的版本，数据被重置

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#64]
### What happened?

两者都是canary

### Platform

Android

### App Version

2.0.5 (906)

**Comment by narumishi** [comment]
请发一下logs/log.log
很疑惑啊，到底是什么原因啊，我就删了一个从者硬币啊

**Comment by narumishi** [comment]
数据没有被清空，获取的根路径发生了变化，等我改回去。
`Android/data/cc.narumi.chaldea/files/`
but now it is `Android/data/cc.narumi.chaldea/files/documents/`

**Comment by narumishi** [comment]
重新下载v2.0.5的apk，已更新

**Comment by dajusha** [comment]
> 重新下载v2.0.5的apk，已更新

好的，修正了就关了吧。
