### ISSUE TITLE
[Bug]: 剧情进度列表的翻译问题

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#65]
### What happened?

在设定可选free本时，进度中的平安京大概应该是Lostbelt 5.5？

![Screenshot_20220731-212106](https://user-images.githubusercontent.com/12206161/182060333-229e4e92-72ea-4fc3-80cb-aaf14bb28da1.jpg)

### Platform

web, Android, Windows

### App Version

2.0.9，以前版本好像也有，忘说了

**Comment by narumi147** [comment]
你得好好问问台服的运营方为什么把平安京的填了`Lostbelt No.1`的名字，美服好歹用的是`Lostbelt ?` 
目前已经把未开放的主线屏蔽了，翻译改回去了
