### ISSUE TITLE
[FEATURE]MacOS App & IOS App 横屏时的UI适配

### ISSUE THREAD

**Issue by tyvens** [chaldea-center/chaldea#66]
手机横屏时以及macos的app打开时, 右侧图标区域显得有点多
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/23257014/182283703-48683e55-fc19-4c2c-8af1-f4d55d28ca24.png">
可以理解右侧作为详情展示的模块, 但是不点选时是否可以让屏幕利用率更高一些?或者提供自定义区域大小?(拖动边界)

**Comment by narumi147** [comment]
你是说有右侧详情页的时候左侧变窄，无的时候左侧变宽？
——目前的框架做不了。中间并不是分界线，而是一个页面只显示左侧并右侧展示图标，或者只在右侧显示，左侧为透明的，因此能看到下层页面。所以也无法做到拖动中间更改，

左右宽度比例是可以调，加个设置选项就好，目前38:62，但只能是全局，不能动态调整。

**Comment by narumi147** [comment]
try canary release: Settings->DisplaySettings->SplitScreenRatio

**Comment by tyvens** [comment]
> try canary release: Settings->DisplaySettings->SplitScreenRatio

已测试,  可以达到预期效果,  感谢
