### ISSUE TITLE
[Bug]: 不知道是人为还是系统读取的原因，本次美服DL活动中自动人偶类型识别错误。

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#67]
### What happened?

![Screenshot_20220812-124218](https://user-images.githubusercontent.com/12206161/184414346-025523e6-e3f8-4e64-8ae4-568a74f17d63.jpg)

如图，需要打的自动人偶任务被识别为不知道是什么的2718，下一步无法规划。

而如果手动加入自动人偶类型任务就可以正常运行。

### Platform

iOS, Android, Windows

### Which game server is related to this issue?

NA

### App Version

2.0.9 910

**Comment by narumi147** [comment]
美服自作主张改了，2718大概是1105的一个超集，虽然日服已经有“敌人”包含了2718这个特性（作为一个Servant），但是主线free的敌人并有添加/更新这一特性(作为一个QuestEnemy)
https://apps.atlasacademy.io/db/JP/entities?trait=2718
https://apps.atlasacademy.io/db/JP/quests?type=free&enemyTrait=2718
应用中主线free本相关均采用日服数据，所以是没有2718的。
虽然换成1105automata可以规划，但无法保证美服只是简单的把1105换成2718。
https://apps.atlasacademy.io/db/JP/entities?trait=1105
https://apps.atlasacademy.io/db/NA/entities?trait=2718

**Comment by dajusha** [comment]
> 美服自作主张改了，2718大概是1105的一个超集，虽然日服已经有“敌人”包含了2718这个特性（作为一个Servant），但是主线free的敌人并有添加/更新这一特性(作为一个QuestEnemy) https://apps.atlasacademy.io/db/JP/entities?trait=2718 https://apps.atlasacademy.io/db/JP/quests?type=free&enemyTrait=2718 应用中主线free本相关均采用日服数据，所以是没有2718的。 虽然换成1105automata可以规划，但无法保证美服只是简单的把1105换成2718。 https://apps.atlasacademy.io/db/JP/entities?trait=1105 https://apps.atlasacademy.io/db/NA/entities?trait=2718

了解。
