### ISSUE TITLE
[Bug]: 【每日任务AP减半】活动相关的问题

### ISSUE THREAD

**Issue by CuteLuoBo** [chaldea-center/chaldea#68]
### What happened?

- 实际国服最近有“新人御主应援”的每日任务AP减半活动，但在chaldea.center里面没有找到。
![image](https://user-images.githubusercontent.com/44561136/185540878-36371a8d-2d8a-48a5-a0ea-f6aa4def4ea4.png)
![image](https://user-images.githubusercontent.com/44561136/185541998-b8b59a49-5de4-44c0-88ae-075405ce4abc.png)

- 在chaldea.center里面查询每日任务 Free本，仍然是显示40AP。同时切换首选区服为国服时，对于国服已开放的free本，依然是默认是显示日服（可能也跟国服无数据有关）
![image](https://user-images.githubusercontent.com/44561136/185541235-e3857d28-58ba-4025-bb19-3696327076dd.png)
- 在使用规划材料时功能，因为修炼本的AP还是40，可能会影响到刷本的素材效率规划。
![image](https://user-images.githubusercontent.com/44561136/185541692-193c77c4-5a62-412b-b9f9-60b81782ddbb.png)

---
对于此类活动，个人觉得可以添加一个切换 每日任务/主线Free AP减半的功能按钮来应对相关情况

### Platform

web

### Which game server is related to this issue?

CN

### App Version

v2.0.10(911)

**Comment by narumi147** [comment]
1. 活动只会显示有内容的（商店、池子、任务等等），减半活动没有任何实质性内容。
2. 首选区服指的是进入该页面默认显示该区服的关卡信息，至于真实显示的是右上角下拉按钮的“日服”。即使你选了国服，也是40AP。减半是40/2=20算出来的，而不是直接将关卡数据改成20。
3. 本来早就想在规划求解中加一个每日关卡减半的选项~~去年~~， 但是一直忘了 🤣 这次会记得加的

**Comment by CuteLuoBo** [comment]
> 1. 活动活动，减少有内容的商场子、）半显示没有任务、任何内容。
> 2. 首区服是进入该页面的默认页面默认显示该服区显示信息，至于真实显示的按钮的“日服”。即使你选择了40AP。20算出来的，而不是直接将关卡数据改成20 。
> 3. 原来本来想在计划中减半的每日关卡选项~去年~，一直存在🤣这一次会记得加的

ok，麻烦了
![2(8`V0G2UKYHIL6O7Y{(3FU](https://user-images.githubusercontent.com/44561136/185549546-14330b57-a466-47ba-8c38-fd2ec3f16e27.jpg)

**Comment by narumi147** [comment]
pls try canary release & feedback wanted
