### ISSUE TITLE
[Bug]: 抓包之后的素材更新

### ISSUE THREAD

**Issue by xinnan** [chaldea-center/chaldea#69]
### What happened?

当第二次抓包中的某个素材为0的时候，导入之后并不会更新该素材的数量，而是保持素材数量不变

### Platform

Windows

### Which game server is related to this issue?

CN

### App Version

2.0.10（911）

**Comment by narumi147** [comment]
对，没记错的话确实<=0的素材并不会更新 🤔 我不确定当一个素材为0时服务器是返回了0还是干脆没有返回这条记录。
如果是返回了0，那ok我可以把=0加上，但如果是后者，则无法判定了。
如可以的话，请你检查下返回的数据里，userItem部分有没有包含你说的那个0的素材，素材id可以在app内看

**Comment by xinnan** [comment]
应该是没有返回这条记录了...
这里是不是应该再for一遍原来的素材， 新的没有了就变成0？...

**Comment by narumi147** [comment]
什么叫“原来的素材”？
如果是遍历所有素材，但又不希望动未实装的素材
如果是拿上次抓包得结果做参考这事有点不合理，为啥要一直存上次的结果，另外app是支持多账号多服务器的，更不能用
