### ISSUE TITLE
[Bug]: 特定项目时间错误

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#70]
### What happened?

在游戏数据页面中，第二行效率剧场的时间为“1969-12-31”

### Platform

Windows

### App Version

2.1.0 913

**Comment by dajusha** [comment]
另：在2.1更新后，win和androidd平台上都发现：

游戏数据更新为9月18日04：14后再次点击更新还是可以更新为同一个数据，app不会阻止。

游戏数据更新后，主界面所有按钮为灰色不可用，必须强行关闭app再启动。

**Comment by narumi147** [comment]
不明白 非常不明白
1. 为什么会出现加载数据只加载了一部分（你的是效率剧场数据没加载）
2. 有的明明数据无效(timestamp=0&无从者无素材)，此时应该禁用了一切与数据有关的入口，但仍然有不少人进去了导入抓包数据的页面导致出错。
这两问题在很早以前就有了。百思不得其解，第一个复现比较困难，因为我还不知道原因。第二个我希望有经历的人描述下自己的操作过程（进了什么页面，点了什么操作等等）

**Comment by dajusha** [comment]
> 

现在重启app后可见剧场的时间为0715了，看来原因就是app大更新后数据没更新完成看起来就那样，更新成功就好了。

你说的第二点没看懂（我没用过抓包功能），进哪里去？

**Comment by narumi147** [comment]
“再次点击更新还是可以更新为同一个数据”
这个没明白，截个图顺便贴下log.log文件？按理说无新版本直接弹出提醒。

关于第二点上面贴了个图，这个页面按理说数据无效(主页面灰色)时是进不去的。应该是更新前已经进入该页面，此时弹窗提醒更新。

**Comment by dajusha** [comment]
`├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:180)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:184)
├ [2022-09-18 12:22:30.292][INFO] Unique ID: 45D6AA3B-04C8-5AF6-B663-E98B087C1576
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:84)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:186)
├ [2022-09-18 12:22:30.294][INFO] Resolved app version: cc.narumi.chaldea 2.0.11+912 01ab40 - 8/24/2022
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:231)
│ #1   GameDataLoader.reload (package:chaldea/app/tools/gamedata_loader.dart:74)
│ #2   _BootstrapPageState.onDataReady (package:chaldea/app/modules/home/bootstrap.dart:457)
├ Exception: No data loaded
├ [2022-09-18 12:22:45.003][ERROR] load gamedata(false)
└-----------------------------------------------------------------------------------------------------------------------
├ #0   _ChaldeaState.setOnWindowClose.<anonymous closure> (package:chaldea/app/chaldea.dart:187)
│ #1   _ChaldeaState.setOnWindowClose.<anonymous closure> (package:chaldea/app/chaldea.dart:186)
├ [2022-09-18 12:23:04.487][INFO] closing desktop app...
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:180)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:184)
├ [2022-09-18 12:23:53.524][INFO] Unique ID: 45D6AA3B-04C8-5AF6-B663-E98B087C1576
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:84)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:186)
├ [2022-09-18 12:23:53.526][INFO] Resolved app version: cc.narumi.chaldea 2.1.0+913 9d519a - 9/18/2022
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:240)
│ #1   GameDataLoader.reload (package:chaldea/app/tools/gamedata_loader.dart:74)
├ [2022-09-18 12:24:07.606][INFO] Updating dataset(2022-09-18 04:14): 7 files updated
└-----------------------------------------------------------------------------------------------------------------------
├ #0   GameDataLoader._loadJson (package:chaldea/app/tools/gamedata_loader.dart:240)
│ #1   GameDataLoader.reload (package:chaldea/app/tools/gamedata_loader.dart:74)
├ [2022-09-18 12:24:22.163][INFO] Updating dataset(2022-09-18 04:14): 0 files updated
└-----------------------------------------------------------------------------------------------------------------------
├ #0   _ChaldeaState.setOnWindowClose.<anonymous closure> (package:chaldea/app/chaldea.dart:187)
│ #1   FlutterWindowClose.setWindowShouldCloseHandler.<anonymous closure> (package:flutter_window_close/flutter_window_close.dart:63)
├ [2022-09-18 12:26:25.849][INFO] closing desktop app...
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadUniqueId (package:chaldea/packages/app_info.dart:180)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:184)
├ [2022-09-18 12:26:31.408][INFO] Unique ID: 45D6AA3B-04C8-5AF6-B663-E98B087C1576
└-----------------------------------------------------------------------------------------------------------------------
├ #0   AppInfo._loadApplicationInfo (package:chaldea/packages/app_info.dart:84)
│ #1   AppInfo.resolve (package:chaldea/packages/app_info.dart:186)
├ [2022-09-18 12:26:31.409][INFO] Resolved app version: cc.narumi.chaldea 2.1.0+913 9d519a - 9/18/2022
└-----------------------------------------------------------------------------------------------------------------------
├ #0   _ChaldeaState.setOnWindowClose.<anonymous closure> (package:chaldea/app/chaldea.dart:187)
│ #1   FlutterWindowClose.setWindowShouldCloseHandler.<anonymous closure> (package:flutter_window_close/flutter_window_close.dart:63)
├ [2022-09-18 12:31:14.876][INFO] closing desktop app...
└-----------------------------------------------------------------------------------------------------------------------
`

此段时间的log在上面。

已经更新完截不了了。描述起来就是：
点一下更新那行，看着进度到100%，出对话框提示更新到了09180414。确定。然后再点一下更新那行，又重新下载到了100%，出对话框提示从09180414更新到了09180414。
然后好吧没有可更新的了，回到主菜单一看全都不可用。Windows关了再开就行了，android边缘划一下，没有真的退出，再开还是灰的，需要在app窗口列表里杀一下再开才正常。

**Comment by dajusha** [comment]
当然现在再去点更新就会正常提示 已经是最新版本

**Comment by narumi147** [comment]
原因大概明白了，app启动->离线加载本地数据->后台更新数据开始(只下载但不加载, 所以得到空数据)->手动更新，此时后台更新未结束，更新数据是单例的，都是同一个任务，所以直接拿到后台更新的空数据。

---
ps `这个字符用来包代码块或日志，如果成段的话用三个连续的这符号，要换行，开始的三个点后面可以写语言类型(可选)

例如:
```python
print("hello")
```
<img width="106" alt="image" src="https://user-images.githubusercontent.com/56487872/190921642-1d5e95fa-36c7-4098-81ad-82ef31d64c20.png">

**Comment by dajusha** [comment]
> 原因大概明白了，app启动->离线加载本地数据->后台更新数据开始(只下载但不加载, 所以得到空数据)->手动更新，此时后台更新未结束，更新数据是单例的，都是同一个任务，所以直接拿到后台更新的空数据。
> 
> ps `这个字符用来包代码块或日志，如果成段的话用三个连续的这符号，要换行，开始的三个点后面可以写语言类型(可选)
> 
> 例如:
> 
> ```python
> print("hello")
> ```
> 
> <img alt="image" width="106" src="https://user-images.githubusercontent.com/56487872/190921642-1d5e95fa-36c7-4098-81ad-82ef31d64c20.png">

学习了。
发布log时候就是想隔开正文避免混淆，结果用单个 ‘ 做代码段导致段落全乱掉了，就马上又编辑掉了。
