### ISSUE TITLE
[FEATURE]建议加一个功能：强化从者时显示素材库尚缺乏多少素材。

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#71]
**Describe the solution you'd like**

目前点击从者，随意选择一些强化，点一下确定，可在弹出对话框见到“强化将扣除以下素材”，其中列出qp和各种素材将会扣除的数目。

建议在图标上方加一个数字显示扣除后将会剩余的数目，只显示负数项目也行。
这样可以不需最终点击确定，就可以获知如果要如此强化，还缺乏哪些数目的素材。

**Comment by narumi147** [comment]
那就和旁边的“需求”按钮一样，显示一个 “减去库存” 的按钮呗，将要扣除20个，库存8个，则只显示12个（不足的），足够的则不显示。
<img width="372" alt="image" src="https://user-images.githubusercontent.com/56487872/193542737-b27303c4-ed9c-4aa9-b6cc-6cea608c0e00.png">
<img width="281" alt="image" src="https://user-images.githubusercontent.com/56487872/193542789-4cbfa579-4792-4274-88af-5ee7e37a6b59.png">

**Comment by dajusha** [comment]
好啊，这个方法可以。

**Comment by narumi147** [comment]
check preview version
