### ISSUE TITLE
[Bug]: LateInitializationError for '_defaultBox' when accessing https://chaldea.center

### ISSUE THREAD

**Issue by Justus188** [chaldea-center/chaldea#73]
### What happened?

LateInitializationError for '_defaultBox' when accessing https://chaldea.center.

![image](https://user-images.githubusercontent.com/54542803/195965703-7337ec83-c717-44de-8825-4c6e9a026e11.png)

### Platform

Windows

### Device Info

Windows 10

### Which game server is related to this issue?

NA

### App Version

2.1.2

**Comment by narumi147** [comment]
fixed
