### ISSUE TITLE
[FEATURE]新加入的剧情文本和背景图很棒，希望在文本页面末尾加上“下一节”之类的按钮。

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#74]
不然就需要退出来两下才能换小节看下一段。

**Comment by dajusha** [comment]
另：

每次进入不同文本页面时都默认是日文，只好手动改成中文。不知道哪里能改设置默认语言。

**Comment by narumi147** [comment]
1. 如果从关卡页面进入，则会使用关卡所显示的区服。关卡默认显示区服在关卡页面的菜单里可以设置。
2. 如果从剧情列表进，则会使用优先使用设置中的“首选翻译”的第一种语言，如果该剧情所在关卡的活动/主线未在该区服开放，则使用日服。

**Comment by dajusha** [comment]
> 1. 如果从关卡页面进入，则会使用关卡所显示的区服。关卡默认显示区服在关卡页面的菜单里可以设置。
> 2. 如果从剧情列表进，则会使用优先使用设置中的“首选翻译”的第一种语言，如果该剧情所在关卡的活动/主线未在该区服开放，则使用日服。

目前app的设置是：
当前帐号为“美服”
首选翻译为“台服”
app语言为“简体中文”

然后在主菜单点击剧情按钮，点击“主线记录/限时活动”，可以看到各个tab中显示的关卡名称为繁中（符合首选翻译设置），在主线记录tab中选择“第一特异点”为例，点击“主线关卡”，可见到各节列表，随意点击一节，可见右上变为“日服”，此时进入任一剧情，右上为“日服”，且文本为日文。

如果在任一节内将右上改为“国服”，可在当前节查看中文剧情文本。但是回到小节列表，再进入任一小节，右上又变为“日服”。


所以：
1. 关卡默认显示区服可以设置，但每次都要从日服改。
2. 从剧情列表进，并未使用首选翻译语言。由于是查看第一特异点，不存在未开放问题。

**Comment by dajusha** [comment]
是我傻了，我刚发现主线剧情那行往下有个单独的“剧情”按钮，里面仅列出剧情项目，翻译也是跟着我设置的台服走的。

**Comment by dajusha** [comment]
那么从这个入口去看剧情，语言的问题就解决了。

仍然需要标题所说的直接进入下一页剧情的按钮。

**Comment by narumi147** [comment]
我说的关卡页面设置指的是关卡页右上角菜单打开的“首选区服”这一设置。而菜单旁边的直接选区服的下拉按钮不算设置，只是表示当前显示区服的数据
![999FEE64-84F9-489D-A48B-57C387FBBCCA](https://user-images.githubusercontent.com/56487872/196018493-494b2500-da0b-4349-84d7-5a70f834db94.jpeg)

下一页什么的稍后再加，考虑到有一个循环问题，因为有些关卡有分支关卡（根据选项不同打不同的本），分支关卡可能排在最终节之后但剧情文本又是一样的，造成循环

**Comment by dajusha** [comment]
下一页的问题理解了。

试了下你图里的这个设置，完全解决了语言默认问题！
就是这个设置藏得有点太深了（我原来的设置是“默认”，估计从来没见过），能够移动到总设置页面就好了。

**Comment by dajusha** [comment]
> 加了，循环就循环吧。 典型例子就是日服现在的活动，永远无法达到第二节的真实。 <img alt="image" width="365" src="https://user-images.githubusercontent.com/56487872/196257555-37fd27ce-0415-4b33-81c3-323a12a9ce56.png">

试用了新版，发现了其他相关bug：

随便点了个旧活动（天草白情），在剧情里点一节进去是默认台服翻译，但是在页面点下一节，出现的下一节是日语文本，手动改成中文，再点下下节又变成日语。

**Comment by narumi147** [comment]
😞  构思的时候就想到了这个事，写的时候忘记了==、修了
