### ISSUE TITLE
[Bug]: Servant Details page scroll issue (windows)

### ISSUE THREAD

**Issue by Crescent07891** [chaldea-center/chaldea#75]
### What happened?

When scrolling through a servants details page the application would jump back to a specific point on the page repeatedly. Scrolling down or up and letting go of the track pad would cause the page to jump pack to about the middle of whichever tab was being viewed. Even if the tab was scrolling properly sometimes when trying to click on a element within one the tabs, the page would jump again. 

https://user-images.githubusercontent.com/107718579/207241602-1e63a0cc-aab0-4d56-9baf-70b6376eb32a.mp4

Attached is a screen recording of attempted scrolling through the voice tab of a servants detail page 

Unsure if its something with the application or my computer/track pad

### Platform

Windows

### Device Info

Windows 10 22H2

### Which game server is related to this issue?

NA

### App Version

2.2.0

**Comment by narumi147** [comment]
It affects Windows/macOS trackpad.
Fixed by flutter team, refer the above linked issue for details. And canary preview should work.

**Comment by narumi147** [comment]
check v2.2.1
