### ISSUE TITLE
Upload Active Skill/Append Screenshot 524 Timeout

### ISSUE THREAD

**Issue by Konahrik13** [chaldea-center/chaldea#76]
### What happened?

When trying to upload the Servants for the Active Skill and Append Screenshot importer an error pops up that says:

[NetworkError] DioError
[DioErrorType.response]: Http status
error [524]

I have the grid on the second option and I made sure that none of them were cut off to show their whole icon. The Item part worked fine, I don't know what's going wrong with the other two.

### Platform

Android

### Device Info

Galaxy A52 5G

### Which game server is related to this issue?

NA

### App Version

2.2.0 (916)

**Comment by narumi147** [comment]
tell me your uuid, and your upload time(with time zone)
about how to get your device's uuid, check https://docs.chaldea.center/faq.html

**Comment by Konahrik13** [comment]
UUID: 913C03E3-37FE-5A5D-A31D-9FC3BE9C403D

I tried a Append upload at 11:22pm EST.

**Comment by narumi147** [comment]
how many files did you uploaded?

**Comment by Konahrik13** [comment]
I believe 7 screenshots? It took over a minute to show the error after trying to upload.

**Comment by narumi147** [comment]
CN server or global server?

**Comment by Konahrik13** [comment]
Global. I play NA.

**Comment by narumi147** [comment]
okay chaldea server is my own server, no related to your game server.

Global server is deployed on Cloudflare, the default timeout is 100s, I cannot change it unless to buy Cloudflare Enterprise. 

7 files seem too big to upload and recognize in 100s, and 524 error occurs.
- 04:24:32 +00  -  recognization finished
- 04:24:15 +00 - timeout

Just upload fewer files once, like 4 at once.
