### ISSUE TITLE
[Bug]: 素材规划计算数目不符，疑为小数取整问题

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#78]
### What happened?

规划设置素材需求数目为：

![xuqiu](https://user-images.githubusercontent.com/12206161/212243593-bf7e8ad2-2842-4222-a8f4-eb90a807a691.jpg)

计算得到结果：

![guihua](https://user-images.githubusercontent.com/12206161/212243639-2939b113-5bba-4424-b0df-6c8be737f025.jpg)

可见骨头和鬼灯的总和都比需求数目少1个。

### Platform

Windows

### App Version

2.2.1.917

**Comment by narumi147** [comment]
设计之初大概就是这样的，目标3个，算出来A1.5+B1.6=3.1>3，为了保险起见，1.5个只显示1个。主要是写小数不好看。
缺少的可能只是一句提示，显示的整数与实际计算结果有±1之差之类的话，不过本来就是看脸掉落，1个意义不大，就一直懒得写╮(╯▽╰)╭

**Comment by dajusha** [comment]
> 

要不干脆向上取整吧，用户看着按计划会多掉还能更高兴，就算没掉也不会来找你赔（

**Comment by narumi147** [comment]
不了，下面加了句提示就
