### ISSUE TITLE
[BUG] 1.5.8材料对应错误

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#8]
**Describe the bug**
1.5.8材料规划似乎材料对应有问题，在规划需求时数目是对的，但计算出来的free本需要打多少次的数目明显不正确。

![1](https://user-images.githubusercontent.com/12206161/134095209-6c68f6fd-8bda-4d91-8268-547ef379d2be.png)
![2](https://user-images.githubusercontent.com/12206161/134095210-58e4e3b5-e5f6-4d7d-a946-49c6cc09fea0.png)
![3](https://user-images.githubusercontent.com/12206161/134095211-18dc7aa4-08a4-452d-b4f6-56c9f659aeeb.png)

可见图中需求幼体10个，盘子629个，在右侧需求显示没有问题，但是规划计算结果是以幼体需要629来计算的。

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Version 1.5.8

**Additional context**

**Comment by narumishi** [comment]
好奇怪，可以保持需求是这个数不要改动，然后再设置-反馈里发送一下，我好检查下日志，仅用截图中的素材和数目无法复现这个问题。

**Comment by narumishi** [comment]
修好了，上次改成了和周常规划计算一套求解模型，但是切换过去的时候LP参数传错的==、
我试了几遍没有问题在于我测试的时候只添加了普通素材，没有技能石和棋子，这时候结果都是一样的……

**Comment by dajusha** [comment]
> 修好了，上次改成了和周常规划计算一套求解模型，但是切换过去的时候LP参数传错的==、
> 我试了几遍没有问题在于我测试的时候只添加了普通素材，没有技能石和棋子，这时候结果都是一样的……

谢谢，请问何时更新到客户端？

**Comment by narumishi** [comment]
https://wws.lanzoui.com/b01tuahmf
password: chaldea

可以先从这里下载1.5.9-preview，也麻烦请你测试下这个功能是否真的修复了

**Comment by dajusha** [comment]
> https://wws.lanzoui.com/b01tuahmf
> password: chaldea
> 
> 可以先从这里下载1.5.9-preview，也麻烦请你测试下这个功能是否真的修复了

试验了，规划结果对应没有问题了。但是有个新问题：

![Screenshot 2021-09-21 114332](https://user-images.githubusercontent.com/12206161/134212550-d00d2d68-dfcf-4f63-83b6-f5b2a90ea92c.png)
![Screenshot 2021-09-21 113842](https://user-images.githubusercontent.com/12206161/134212553-f4a0f3a4-d048-4ed3-a7d1-ea0ba2ab06a4.png)

一个图是1.5.9 preview的规划结果，另一个是旁边chaldea-windows.old（实际是1.5.6）的规划结果，两者的需求数字是一样的，但是规划结果有区别，是算法换了导致的么？

**Comment by dajusha** [comment]
> 1.5.8是对1.5.7的紧急修复，按理说这部分应该是一样的。
> 1.5.7之后新加入了6周年新掉落数据和旧数据的选择。默认使用新数据，旧数据只包含2.5.5及之前的信息。
> 
> 如果要和1.5.6对比：
> 
> 1. 在输入页设置里关闭使用新掉落数据
> 2. 去除所有2.6的素材
> 3. 1.5.6使用的MC于2021.5.31在效率剧场获取的数据，而1.5.8是直接从效率剧场获取，其中旧版数据最后更新为2021.8.2，存在细微区别，但应该不大

1.5.9中关闭使用新掉落数据之后就基本一样了，虽仍然有一个两个的区别，不过无关紧要。

**Comment by narumishi** [comment]
1.6.0 released
