### ISSUE TITLE
[BUG]无法正常运行

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#9]
**Describe the bug**
chaldea-1.6.0-windows.zip解压覆盖原1.5.9文件夹内容，运行chaldea.exe直接变截图

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - App Version [v1.6.0+600]
![Screenshot 2021-09-21 204823](https://user-images.githubusercontent.com/12206161/134270764-b955a619-f151-4358-b076-fec261b108a0.png)

**Comment by narumishi** [comment]
凎，重新上传了，麻烦到release里重新下载一下，没人测试太容易出问题了，那么多平台自己也没有一个个测试。

**Comment by narumishi** [comment]
第一次提交1.5.7之后，直接1.5.8，1.5.9，1.6.0反复撤回修bug再提交，已经被自己气死了😭

**Comment by dajusha** [comment]
> 凎，重新上传了，麻烦到release里重新下载一下，没人测试太容易出问题了，那么多平台自己也没有一个个测试。

用新的再次覆盖，运行第一次窗口内白屏卡死，关掉再打开等一下就正常了，目前至少规划这里没问题（

**Comment by dajusha** [comment]
> 第一次提交1.5.7之后，直接1.5.8，1.5.9，1.6.0反复撤回修bug再提交，已经被自己气死了😭

目前这个win版1.6好像没啥毛病，喝点茶去休息一下别上火……
