### ISSUE TITLE
[Bug]: 重复剧情关卡

### ISSUE THREAD

**Issue by dajusha** [chaldea-center/chaldea#92]
### What happened?

关卡配置，2.6，主线关卡，拉到最下，卫生下面还有一个**第14节**。上面15节之前也有，所以下面是多出来的。

### Platform

All

### App Version

2.4.4 936

**Comment by SharpnelXu** [comment]
14节进行度2/5为有分支的剧情，根据玩家所选会有不同的战斗。在源数据中分支类是这样呈现的，所以不是bug。
